"""Generated by Copilot."""

from fastapi import APIRouter

router = APIRouter()


@app.callback
@router.get("/admin/users")
@require_permissions("admin:read")
def list_admin_users():
    return {"users": ["alice", "bob"]}
