from __future__ import annotations

import json
import os
import subprocess
from enum import Enum
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .config import AppConfig, ConfigError, load_app_config
from .context_extractor import ContextExtractor
from .llm_analyzer import LLMAnalyzer, LLMAnalyzerError
from .models import Finding, ProjectScanSummary, ScanReport, normalize_path
from .risk_heuristics import fallback_reasons
from .semgrep_runner import SemgrepError, SemgrepRunner, semgrep_available

app = typer.Typer(help="AION: The Self-Evolving Code Engine. Code Once, Live Forever.", no_args_is_help=True)
stderr_console = Console(stderr=True)
stdout_console = Console()

AI_MARKERS = (
    "generated by",
    "co-authored-by: github-copilot",
    "github-copilot[bot]",
    "@cursor",
    "cursor ai",
)


class Provider(str, Enum):
    anthropic = "anthropic"
    openai = "openai"


@app.callback()
def main() -> None:
    """AION: The Self-Evolving Code Engine. Code Once, Live Forever."""


@app.command()
def scan(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    ai_generated: list[Path] | None = typer.Option(
        None,
        "--ai-generated",
        help="Explicit files or directories to treat as AI-generated. Can be repeated.",
    ),
    provider: Provider | None = typer.Option(None, "--provider", help="LLM provider: anthropic or openai."),
    model: str | None = typer.Option(None, help="Model name. Defaults depend on provider."),
    output: str = typer.Option("text", "--output", help="text or json"),
    verbose: bool = typer.Option(False, "--verbose", help="Print context and raw prompts to stderr."),
) -> None:
    root = target if target.is_dir() else target.parent
    try:
        config = load_app_config(root)
    except ConfigError as exc:
        raise typer.BadParameter(str(exc)) from exc

    resolved_provider = provider or _provider_from_config(config) or Provider.anthropic

    api_key = _resolve_api_key(resolved_provider)
    if not api_key:
        raise typer.BadParameter(
            _missing_api_key_message(resolved_provider)
        )
    resolved_model = model or config.model or _default_model_for_provider(resolved_provider)

    extractor = ContextExtractor(root=root, extra_ignore_patterns=config.ignore_paths)
    context_profile = extractor.extract()

    if verbose:
        stderr_console.print("[bold]Context profile[/bold]")
        stderr_console.print_json(json.dumps(context_profile.summary_payload(), ensure_ascii=False))

    candidate_files = _resolve_target_files(target, config.ignore_paths)
    if not candidate_files:
        _exit_with_summary(ProjectScanSummary(target=normalize_path(target), warnings=["No Python files found."]), output)

    explicit_targets = _expand_explicit_targets(ai_generated or [])
    files_to_scan, detection_warnings = _detect_ai_generated_files(candidate_files, explicit_targets, root)
    summary = ProjectScanSummary(
        target=normalize_path(target),
        files_scanned=len(files_to_scan),
        warnings=detection_warnings,
    )

    runner = SemgrepRunner()
    has_semgrep = semgrep_available()
    if not has_semgrep:
        summary.warnings.append("semgrep is not installed; falling back to LLM-only mode.")

    analyzer = LLMAnalyzer(api_key=api_key, model=resolved_model, provider=resolved_provider.value, verbose=verbose)

    for file_path in files_to_scan:
        report = ScanReport(file=normalize_path(file_path), ai_generated=True)
        semgrep_findings = []
        if has_semgrep:
            try:
                semgrep_findings = runner.run(file_path)
            except SemgrepError as exc:
                summary.warnings.append(f"semgrep failed for {file_path.name}: {exc}")
        report.semgrep_findings = semgrep_findings

        if verbose:
            stderr_console.print(f"[bold]Estimated token cost[/bold] {file_path}: {analyzer.estimate_tokens(file_path, context_profile)}")
            if semgrep_findings:
                stderr_console.print("[bold]Semgrep findings[/bold]")
                stderr_console.print_json(
                    json.dumps([finding.model_dump() for finding in semgrep_findings], ensure_ascii=False)
                )

        try:
            reasons = fallback_reasons(file_path, context_profile)
            if verbose and reasons:
                stderr_console.print(f"[bold]Fallback reasons[/bold] {file_path}: {', '.join(reasons)}")

            should_run_llm = (not has_semgrep) or bool(semgrep_findings) or bool(reasons)
            if not should_run_llm:
                report.mode = "semgrep-only"
                report.findings = []
            else:
                report.findings = analyzer.analyze(
                    file_path,
                    context_profile,
                    semgrep_findings,
                    fallback_signals=reasons,
                    console=stderr_console,
                )
                report.mode = "llm-only" if not has_semgrep else "semgrep+llm"
        except LLMAnalyzerError as exc:
            summary.warnings.append(f"LLM analysis failed for {file_path.name}: {exc}")
            report.mode = "semgrep-only" if has_semgrep else "skipped"

        summary.reports.append(report)

    _exit_with_summary(summary, output)


def _resolve_target_files(target: Path, extra_ignore_patterns: list[str] | None = None) -> list[Path]:
    extra_ignore_patterns = extra_ignore_patterns or []
    if target.is_file():
        return [target] if target.suffix == ".py" else []
    return sorted(
        path
        for path in target.rglob("*.py")
        if not any(part in {".git", ".venv", "venv", "node_modules", "__pycache__"} for part in path.parts)
        if not _matches_any_pattern(path, target, extra_ignore_patterns)
    )


def _matches_any_pattern(path: Path, root: Path, patterns: list[str]) -> bool:
    try:
        relative = path.relative_to(root if root.is_dir() else root.parent).as_posix()
    except ValueError:
        relative = path.as_posix()
    for pattern in patterns:
        if Path(relative).match(pattern) or Path(path.name).match(pattern):
            return True
    return False


def _resolve_api_key(provider: Provider) -> str | None:
    if provider == Provider.anthropic:
        return os.getenv("ANTHROPIC_API_KEY")
    if provider == Provider.openai:
        return os.getenv("OPENAI_API_KEY")
    return None


def _missing_api_key_message(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "ANTHROPIC_API_KEY is not set. Export it before running, for example: export ANTHROPIC_API_KEY=your_key"
    if provider == Provider.openai:
        return "OPENAI_API_KEY is not set. Export it before running, for example: export OPENAI_API_KEY=your_key"
    return "Provider API key is not set."


def _default_model_for_provider(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "claude-3-5-sonnet-latest"
    if provider == Provider.openai:
        return "gpt-4.1"
    raise ValueError(f"unsupported provider: {provider}")


def _provider_from_config(config: AppConfig) -> Provider | None:
    if config.provider is None:
        return None
    try:
        return Provider(config.provider)
    except ValueError as exc:
        raise typer.BadParameter(f"unsupported provider in .aion.yaml: {config.provider}") from exc


def _expand_explicit_targets(targets: list[Path]) -> set[str]:
    expanded: set[str] = set()
    for target in targets:
        if target.is_dir():
            for path in target.rglob("*.py"):
                expanded.add(normalize_path(path))
        elif target.suffix == ".py":
            expanded.add(normalize_path(target))
    return expanded


def _detect_ai_generated_files(
    candidates: list[Path],
    explicit_targets: set[str],
    root: Path,
) -> tuple[list[Path], list[str]]:
    warnings: list[str] = []
    if explicit_targets:
        selected = [path for path in candidates if normalize_path(path) in explicit_targets]
        if not selected:
            warnings.append("No Python files matched --ai-generated targets.")
        return selected, warnings

    selected = [path for path in candidates if _has_ai_marker(path) or _git_history_has_ai_marker(path, root)]
    if selected:
        return selected, warnings

    warnings.append("No AI-generated markers found; scanning all Python files.")
    return candidates, warnings


def _has_ai_marker(path: Path) -> bool:
    try:
        content = path.read_text(encoding="utf-8", errors="ignore")[:2000].lower()
    except OSError:
        return False
    return any(marker in content for marker in AI_MARKERS)


def _git_history_has_ai_marker(path: Path, root: Path) -> bool:
    command = [
        "git",
        "-C",
        str(root),
        "log",
        "--format=%an%n%B",
        "--",
        str(path),
    ]
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
    except OSError:
        return False
    if result.returncode != 0:
        return False
    history = result.stdout.lower()
    return "github-copilot" in history or "cursor" in history


def _exit_with_summary(summary: ProjectScanSummary, output: str) -> None:
    if output == "json":
        stdout_console.print_json(summary.model_dump_json())
        raise typer.Exit(code=0)

    for warning in summary.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    if summary.files_scanned == 0:
        stdout_console.print(Panel("No Python files were scanned.", title="AION"))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Target: {summary.target}\nFiles scanned: {summary.files_scanned}\nFindings: {summary.finding_count}",
            title="AION",
        )
    )

    rendered = False
    for report in summary.sorted_reports():
        if not report.findings:
            continue
        rendered = True
        table = Table(title=report.file)
        table.add_column("Severity")
        table.add_column("Line", justify="right")
        table.add_column("Issue")
        table.add_column("Context Gap")
        table.add_column("Fix")
        for finding in sorted(report.findings, key=_severity_sort_key):
            table.add_row(
                finding.severity,
                str(finding.line),
                finding.issue,
                finding.context_gap,
                finding.fix,
            )
        stdout_console.print(table)

    if not rendered:
        stdout_console.print("[green]No findings reported.[/green]")


def _severity_sort_key(finding: Finding) -> tuple[int, int]:
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    return order.get(finding.severity, 4), finding.line
