from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .auto_update import AutoUpdateEngine, AutoUpdateResult
from .config import AppConfig, ConfigError, UpdateConfig, load_app_config, load_update_configs
from .context_extractor import ContextExtractor
from .drift_detector import DriftDetector
from .evaluation import compute_repair_metrics, evaluate_repair_cases, load_fixture_cases
from .inbox import EventInbox
from .knowledge_base import KnowledgeBase
from .llm_analyzer import LLMAnalyzer
from .models import (
    ContextProfile,
    EventQueueSummary,
    Finding,
    InboxItem,
    OrchestrationResult,
    OrchestrationEvent,
    PatchArtifact,
    ProjectScanSummary,
    ReleaseCandidate,
    RepairAttemptRecord,
    RepairSession,
    RunIncidentResult,
    ScanReport,
    SecuritySnapshot,
    VerificationResult,
    normalize_path,
)
from .orchestrator import Orchestrator
from .repair import IncidentDetector, PatchGenerator, RepairExecutor, Verifier
from .release_manager import ReleaseManager
from .semgrep_runner import SemgrepRunner, semgrep_available
from .webhook import WebhookEventServer

app = typer.Typer(help="AION: The Self-Evolving Code Engine. Code Once, Live Forever.", no_args_is_help=True)
stderr_console = Console(stderr=True)
stdout_console = Console()

AI_MARKERS = (
    "generated by",
    "co-authored-by: github-copilot",
    "github-copilot[bot]",
    "@cursor",
    "cursor ai",
)

# Directory names that are never scanned regardless of scan target.
# Users can extend exclusions further via ``ignore_paths`` in .aion.yaml.
EXCLUDED_DIRS: frozenset[str] = frozenset({
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".nox",
    ".tox",
    "site-packages",
    "dist-packages",
})


class Provider(str, Enum):
    anthropic = "anthropic"
    openai = "openai"
    gemini = "gemini"
    azure = "azure"
    deepseek = "deepseek"
    qwen = "qwen"


@app.callback()
def main() -> None:
    """AION: The Self-Evolving Code Engine. Code Once, Live Forever."""


@app.command()
def scan(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    ai_generated: list[Path] | None = typer.Option(
        None,
        "--ai-generated",
        help="Explicit files or directories to treat as AI-generated. Can be repeated.",
    ),
    provider: Provider | None = typer.Option(None, "--provider", help="LLM provider: anthropic, openai, gemini, azure, deepseek, or qwen."),
    model: str | None = typer.Option(None, help="Model name. Defaults depend on provider."),
    output: str = typer.Option("text", "--output", help="text or json"),
    verbose: bool = typer.Option(False, "--verbose", help="Print context and raw prompts to stderr."),
) -> None:
    root = target if target.is_dir() else target.parent
    try:
        config = load_app_config(root)
    except ConfigError as exc:
        raise typer.BadParameter(str(exc)) from exc

    resolved_provider = provider or _provider_from_config(config) or _auto_detect_provider()

    api_key = _resolve_api_key(resolved_provider)
    if not api_key:
        raise typer.BadParameter(
            _missing_api_key_message(resolved_provider)
        )
    resolved_model = model or config.model or _default_model_for_provider(resolved_provider)

    extractor = ContextExtractor(root=root, extra_ignore_patterns=config.ignore_paths)
    context_profile = extractor.extract()

    if verbose:
        stderr_console.print("[bold]Context profile[/bold]")
        stderr_console.print_json(json.dumps(context_profile.summary_payload(), ensure_ascii=False))

    candidate_files = _resolve_target_files(target, config.ignore_paths)
    if not candidate_files:
        _exit_with_summary(ProjectScanSummary(target=normalize_path(target), warnings=["No Python files found."]), output)

    explicit_targets = _expand_explicit_targets(ai_generated or [])
    files_to_scan, detection_warnings = _detect_ai_generated_files(candidate_files, explicit_targets, root)
    summary = ProjectScanSummary(
        target=normalize_path(target),
        files_scanned=len(files_to_scan),
        warnings=detection_warnings,
    )

    runner = SemgrepRunner() if semgrep_available() else None
    has_semgrep = runner is not None
    if not has_semgrep:
        summary.warnings.append("semgrep is not installed; falling back to LLM-only mode.")

    analyzer = LLMAnalyzer(api_key=api_key, model=resolved_model, provider=resolved_provider.value, verbose=verbose)
    detector = IncidentDetector(semgrep_runner=runner, llm_analyzer=analyzer)

    for file_path in files_to_scan:
        report = ScanReport(file=normalize_path(file_path), ai_generated=True)
        if verbose:
            stderr_console.print(f"[bold]Estimated token cost[/bold] {file_path}: {analyzer.estimate_tokens(file_path, context_profile)}")
        analysis = detector.analyze(file_path, context_profile, console=stderr_console if verbose else None)
        for warning in analysis.warnings:
            summary.warnings.append(f"{file_path.name}: {warning}")
        if verbose and analysis.semgrep_findings:
            stderr_console.print("[bold]Semgrep findings[/bold]")
            stderr_console.print_json(
                json.dumps([finding.model_dump() for finding in analysis.semgrep_findings], ensure_ascii=False)
            )
        if verbose and analysis.fallback_signals:
            stderr_console.print(f"[bold]Fallback reasons[/bold] {file_path}: {', '.join(analysis.fallback_signals)}")
        report.semgrep_findings = analysis.semgrep_findings
        report.findings = analysis.llm_findings
        report.mode = analysis.mode  # type: ignore[assignment]
        report.incidents = analysis.incidents

        summary.reports.append(report)

    _exit_with_summary(summary, output)


@app.command()
def repair(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    artifact_path: Path | None = typer.Option(None, "--artifact-path", resolve_path=True),
    record_path: Path | None = typer.Option(None, "--record-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    plan_only: bool = typer.Option(True, "--plan/--apply", help="Emit a patch artifact without modifying the file."),
) -> None:
    if not plan_only:
        raise typer.BadParameter("Only --plan is supported in the first autonomy release.")

    context_profile = _load_context_profile(target, context_file)
    root = target if target.is_dir() else target.parent
    detector = _build_detector(root)
    record = RepairExecutor(detector=detector).run(target, context_profile, verify=False)
    if artifact_path is not None:
        _write_record(record, artifact_path)
    if record_path is not None:
        _write_record(record, record_path)
    _exit_with_repair_record(record, output)


@app.command()
def verify(
    artifact_path: Path = typer.Option(..., "--artifact-path", exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(artifact_path.read_text(encoding="utf-8"))
    artifact = _artifact_from_payload(payload)
    verification = Verifier().verify(artifact)
    _exit_with_verification(verification, output)


@app.command("run-incident")
def run_incident(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    artifact_path: Path | None = typer.Option(None, "--artifact-path", resolve_path=True),
    record_path: Path | None = typer.Option(None, "--record-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    context_profile = _load_context_profile(target, context_file)
    root = target if target.is_dir() else target.parent
    result = _build_orchestrator(root).run_incident(target, context_profile)
    if artifact_path and result.session.artifact is not None:
        artifact_path.write_text(result.session.model_dump_json(indent=2), encoding="utf-8")
    if record_path is not None:
        _write_record(_record_from_run_result(result, context_profile), record_path)
    _exit_with_run_incident(result, output)


@app.command("repair-eval")
def repair_eval(
    fixtures_root: Path = typer.Argument(Path("tests/fixtures"), exists=True, readable=True, resolve_path=True),
    records_dir: Path | None = typer.Option(None, "--records-dir", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    cases = load_fixture_cases(fixtures_root)
    results = evaluate_repair_cases(cases, verify=True, records_dir=records_dir)
    metrics = compute_repair_metrics(results)
    _exit_with_repair_eval(results, metrics, output)


@app.command("process-event")
def process_event(
    event_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    result_path: Path | None = typer.Option(None, "--result-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspace after processing."),
) -> None:
    payload = json.loads(event_file.read_text(encoding="utf-8"))
    event = Orchestrator().ingest_event(payload)
    repo_root = _resolve_event_root(event)
    orchestrator = _build_orchestrator(repo_root)
    context_profile = _load_context_profile_for_event(event, context_file)
    result = orchestrator.process_event(event, context_profile, repo_root=repo_root)
    if result_path is not None:
        result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
    if cleanup_sandbox:
        orchestrator.cleanup_sandbox(result)
    _exit_with_orchestration_result(result, output)


@app.command("process-event-queue")
def process_event_queue(
    queue_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    results_dir: Path | None = typer.Option(None, "--results-dir", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspaces after processing."),
) -> None:
    payload = json.loads(queue_file.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise typer.BadParameter("queue file must contain a JSON array of events")

    events = [Orchestrator().ingest_event(item) for item in payload]
    orchestrators: dict[str, Orchestrator] = {}

    def context_loader(event: OrchestrationEvent) -> ContextProfile:
        metadata_context = event.metadata.get("context_file")
        context_path = Path(str(metadata_context)).resolve() if metadata_context else None
        return _load_context_profile_for_event(event, context_path)

    def repo_root_loader(event: OrchestrationEvent) -> Path:
        return _resolve_event_root(event)

    results: list[OrchestrationResult] = []
    summary = EventQueueSummary(total_events=len(events))

    for event in events:
        repo_root = repo_root_loader(event)
        key = normalize_path(repo_root)
        orchestrator = orchestrators.setdefault(key, _build_orchestrator(repo_root))
        context_profile = context_loader(event)
        result = orchestrator.process_event(event, context_profile, repo_root=repo_root)
        results.append(result)
        _accumulate_queue_summary(summary, result)
        if results_dir is not None:
            results_dir.mkdir(parents=True, exist_ok=True)
            result_path = results_dir / f"{event.event_id}.json"
            result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
        if cleanup_sandbox:
            orchestrator.cleanup_sandbox(result)

    _exit_with_event_queue_results(results, summary, output)

@app.command("enqueue-event")
def enqueue_event(
    event_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(event_file.read_text(encoding="utf-8"))
    event = Orchestrator().ingest_event(payload)
    item = EventInbox(inbox_root).enqueue(event)
    _exit_with_inbox_item(item, output)


@app.command("list-inbox")
def list_inbox(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    status: str | None = typer.Option(None, "--status", help="pending, processed, or failed"),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    items = EventInbox(inbox_root).list_items(status=status)
    _exit_with_inbox_items(items, output)


@app.command("process-inbox")
def process_inbox(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspaces after processing."),
) -> None:
    inbox = EventInbox(inbox_root)
    pending = inbox.list_items(status="pending")
    orchestrators: dict[str, Orchestrator] = {}
    results: list[OrchestrationResult] = []
    summary = EventQueueSummary(total_events=len(pending))

    for item in pending:
        try:
            repo_root = _resolve_event_root(item.event)
            key = normalize_path(repo_root)
            orchestrator = orchestrators.setdefault(key, _build_orchestrator(repo_root))
            context_profile = _load_context_profile_for_event(item.event, None)
            result = orchestrator.process_event(item.event, context_profile, repo_root=repo_root)
            result_path = inbox.result_file(item)
            result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
            inbox.mark_processed(item, result_path)
            results.append(result)
            _accumulate_queue_summary(summary, result)
            if cleanup_sandbox:
                orchestrator.cleanup_sandbox(result)
        except Exception as exc:  # noqa: BLE001
            inbox.mark_failed(item, str(exc))

    _exit_with_event_queue_results(results, summary, output)


@app.command("create-release-candidate")
def create_release_candidate(
    result_path: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(result_path.read_text(encoding="utf-8"))
    result = OrchestrationResult(**payload)
    candidate = ReleaseManager(releases_root).create_candidate(result)
    _exit_with_release_candidate(candidate, output)


@app.command("list-releases")
def list_releases(
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    state: str | None = typer.Option(None, "--state", help="candidate, approved, executing, completed, rejected, rolled_back"),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidates = ReleaseManager(releases_root).list_candidates(state=state)
    _exit_with_release_candidates(candidates, output)


@app.command("approve-release")
def approve_release(
    candidate_id: str = typer.Argument(...),
    approver: str = typer.Option(..., "--approver"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).approve(candidate_id, approver)
    _exit_with_release_candidate(candidate, output)


@app.command("reject-release")
def reject_release(
    candidate_id: str = typer.Argument(...),
    approver: str = typer.Option(..., "--approver"),
    reason: str = typer.Option(..., "--reason"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).reject(candidate_id, approver, reason)
    _exit_with_release_candidate(candidate, output)


@app.command("advance-release")
def advance_release(
    candidate_id: str = typer.Argument(...),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).advance(candidate_id)
    _exit_with_release_candidate(candidate, output)


@app.command("rollback-release")
def rollback_release(
    candidate_id: str = typer.Argument(...),
    reason: str = typer.Option(..., "--reason"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).rollback(candidate_id, reason)
    _exit_with_release_candidate(candidate, output)


@app.command("plan-defense")
def plan_defense(
    result_path: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    result = OrchestrationResult(**json.loads(result_path.read_text(encoding="utf-8")))
    if result.defense_plan is None:
        event_root = _resolve_event_root(result.event)
        orchestrator = _build_orchestrator(event_root)
        context_profile = _load_context_profile_for_event(result.event, None)
        result = orchestrator.process_event(result.event, context_profile, repo_root=event_root)
    _exit_with_defense_plan(result.defense_plan, output)


@app.command("serve-webhook")
def serve_webhook(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    host: str = typer.Option("127.0.0.1", "--host"),
    port: int = typer.Option(8080, "--port"),
    max_events: int | None = typer.Option(None, "--max-events", min=1),
) -> None:
    server = WebhookEventServer((host, port), inbox_root)
    server.max_events = max_events
    stdout_console.print(Panel(f"Listening on http://{host}:{server.server_port}/events", title="AION Webhook"))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    raise typer.Exit(code=0)


@app.command()
def snapshot(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    name: str = typer.Option("baseline", "--name", help="Snapshot name (used as filename in snapshots dir)."),
    snapshots_dir: Path = typer.Option(Path(".aion/snapshots"), "--snapshots-dir", resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    """Save a point-in-time security snapshot of TARGET for later drift comparison."""
    context_profile = _load_context_profile(target, context_file)
    detector = DriftDetector(snapshots_dir=snapshots_dir)
    snap = detector.snapshot(target, context_profile)
    saved_path = detector.save_snapshot(snap, name=name)

    if output == "json":
        stdout_console.print_json(snap.model_dump_json())
        raise typer.Exit(code=0)

    incident_count = len(snap.incidents)
    file_count = len(snap.file_hashes)
    stdout_console.print(
        Panel(
            (
                f"Target:    {snap.target}\n"
                f"Snapshot:  {saved_path}\n"
                f"Files:     {file_count}\n"
                f"Incidents: {incident_count}\n"
                f"Health:    {snap.health_score:.1%}"
            ),
            title="AION Snapshot",
        )
    )
    raise typer.Exit(code=0)


@app.command()
def drift(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    name: str = typer.Option("baseline", "--name", help="Snapshot name to compare against."),
    snapshots_dir: Path = typer.Option(Path(".aion/snapshots"), "--snapshots-dir", resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    """Compare TARGET's current security state against a saved snapshot."""
    detector = DriftDetector(snapshots_dir=snapshots_dir)
    baseline = detector.load_snapshot(name)
    if baseline is None:
        raise typer.BadParameter(
            f"No snapshot '{name}' found in {snapshots_dir}. Run `aion snapshot` first."
        )
    context_profile = _load_context_profile(target, context_file)
    current = detector.snapshot(target, context_profile)
    report = detector.compare(baseline, current)

    if output == "json":
        stdout_console.print_json(report.model_dump_json())
        raise typer.Exit(code=0)

    delta_str = f"{report.health_delta:+.1%}"
    status = "[red]REGRESSION[/red]" if report.has_regression else "[green]CLEAN[/green]"
    stdout_console.print(
        Panel(
            (
                f"Status:          {status}\n"
                f"Health delta:    {delta_str}  "
                f"({report.baseline_health_score:.1%} → {report.current_health_score:.1%})\n"
                f"New incidents:   {len(report.new_incidents)}\n"
                f"Resolved:        {len(report.resolved_incidents)}\n"
                f"Regressed files: {len(report.regressed_files)}"
            ),
            title="AION Drift Report",
        )
    )
    if report.new_incidents:
        table = Table(title="New Incidents")
        table.add_column("File")
        table.add_column("Issue Type")
        table.add_column("Severity")
        table.add_column("Line", justify="right")
        for incident in report.new_incidents:
            table.add_row(incident.target_file, incident.issue_type, incident.severity, str(incident.line))
        stdout_console.print(table)

    exit_code = 1 if report.has_regression else 0
    raise typer.Exit(code=exit_code)


@app.command()
def watch(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    interval: int = typer.Option(30, "--interval", help="Polling interval in seconds.", min=5),
    snapshots_dir: Path = typer.Option(Path(".aion/snapshots"), "--snapshots-dir", resolve_path=True),
    knowledge_dir: Path = typer.Option(Path(".aion/knowledge"), "--knowledge-dir", resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    auto_repair: bool = typer.Option(True, "--auto-repair/--no-auto-repair", help="Auto-repair detected incidents."),
    max_cycles: int | None = typer.Option(None, "--max-cycles", help="Stop after N cycles (for testing)."),
) -> None:
    """Continuously monitor TARGET for security drift, auto-repairing new incidents."""
    import time

    kb = KnowledgeBase(base_dir=knowledge_dir)
    detector = DriftDetector(snapshots_dir=snapshots_dir)
    context_profile = _load_context_profile(target, context_file)

    # Seed the baseline if one doesn't exist.
    baseline = detector.load_snapshot("watch-baseline")
    if baseline is None:
        baseline = detector.snapshot(target, context_profile)
        detector.save_snapshot(baseline, name="watch-baseline")
        stdout_console.print(
            Panel(
                f"Baseline saved ({len(baseline.incidents)} incidents, health {baseline.health_score:.1%}).",
                title="AION Watch — baseline",
            )
        )

    stdout_console.print(
        Panel(
            f"Watching {target}  (interval={interval}s, auto_repair={auto_repair})",
            title="AION Watch",
        )
    )
    cycle = 0
    try:
        while True:
            if max_cycles is not None and cycle >= max_cycles:
                break
            time.sleep(interval)
            cycle += 1
            context_profile = _load_context_profile(target, context_file)
            current = detector.snapshot(target, context_profile)
            report = detector.compare(baseline, current)

            if report.has_regression:
                stderr_console.print(
                    f"[red]Cycle {cycle}: drift detected — {len(report.new_incidents)} new incident(s), "
                    f"health {report.health_delta:+.1%}[/red]"
                )
                if auto_repair:
                    repaired = 0
                    executor = RepairExecutor(detector=_build_detector(target if target.is_dir() else target.parent), knowledge_base=kb)
                    file_targets = sorted({incident.target_file for incident in report.new_incidents})
                    for target_file in file_targets:
                        file_path = Path(target_file)
                        if file_path.exists():
                            record = executor.run(file_path, context_profile, verify=True)
                            applied_path = _apply_verified_repair(record)
                            if applied_path is not None:
                                repaired += 1
                                stderr_console.print(f"[green]  Applied verified patch to {applied_path}.[/green]")
                    if repaired:
                        stderr_console.print(f"[green]  Applied verified patches to {repaired} file(s).[/green]")
                        # Refresh baseline after successful repairs.
                        refreshed_context = _load_context_profile(target, context_file)
                        baseline = detector.snapshot(target, refreshed_context)
                        detector.save_snapshot(baseline, name="watch-baseline")
                    else:
                        stderr_console.print("[yellow]  No incidents could be auto-repaired; human review required.[/yellow]")
            else:
                stderr_console.print(f"Cycle {cycle}: no drift (health {current.health_score:.1%})")
    except KeyboardInterrupt:
        pass

    stdout_console.print(Panel("Watch stopped.", title="AION Watch"))
    raise typer.Exit(code=0)


@app.command()
def status(
    aion_dir: Path = typer.Option(Path(".aion"), "--aion-dir", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    """Show overall AION engine health: snapshots, knowledge base, and repair history."""
    snapshots_dir = aion_dir / "snapshots"
    knowledge_dir = aion_dir / "knowledge"

    snapshots: list[dict[str, object]] = []
    if snapshots_dir.exists():
        for snap_file in sorted(snapshots_dir.glob("*.json")):
            try:
                snap = SecuritySnapshot.model_validate_json(snap_file.read_text(encoding="utf-8"))
                snapshots.append({
                    "name": snap_file.stem,
                    "created_at": snap.created_at,
                    "health_score": snap.health_score,
                    "incidents": len(snap.incidents),
                    "files": len(snap.file_hashes),
                })
            except (ValueError, KeyError, OSError) as exc:
                stderr_console.print(f"[yellow]warning:[/yellow] could not load snapshot {snap_file.name}: {exc}")
                continue

    kb = KnowledgeBase(base_dir=knowledge_dir)
    kb_summary = kb.summary()

    payload: dict[str, object] = {
        "snapshots": snapshots,
        "knowledge_base": kb_summary,
    }

    if output == "json":
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    if snapshots:
        snap_table = Table(title="Security Snapshots")
        snap_table.add_column("Name")
        snap_table.add_column("Created")
        snap_table.add_column("Files", justify="right")
        snap_table.add_column("Incidents", justify="right")
        snap_table.add_column("Health")
        for s in snapshots:
            snap_table.add_row(
                str(s["name"]),
                str(s["created_at"])[:19],
                str(s["files"]),
                str(s["incidents"]),
                f"{float(str(s['health_score'])):.1%}",
            )
        stdout_console.print(snap_table)
    else:
        stdout_console.print("[dim]No snapshots found. Run `aion snapshot` to create one.[/dim]")

    total_patterns = int(str(kb_summary["total_patterns"]))
    if total_patterns:
        kb_table = Table(title="Repair Knowledge Base")
        kb_table.add_column("Issue Type")
        kb_table.add_column("Strategy")
        kb_table.add_column("✓ Success", justify="right")
        kb_table.add_column("✗ Failed", justify="right")
        for pattern in kb_summary.get("patterns", []):
            if isinstance(pattern, dict):
                kb_table.add_row(
                    str(pattern.get("issue_type", "")),
                    str(pattern.get("strategy", "")),
                    str(pattern.get("success_count", 0)),
                    str(pattern.get("failure_count", 0)),
                )
        stdout_console.print(kb_table)
    else:
        stdout_console.print("[dim]Knowledge base is empty. Repairs are recorded automatically.[/dim]")

    raise typer.Exit(code=0)


@app.command("auto-update")
def auto_update(
    target: Path = typer.Option(Path("."), "--target", "-t", exists=True, resolve_path=True, help="Repository root to scan and fix."),
    dry_run: bool = typer.Option(False, "--dry-run", help="Scan and plan but do not create pull requests."),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    """Scan the repository, generate verified fixes, and create Pull Requests.

    Works like Dependabot: reads ``.aion.yaml`` for configuration (supports both
    the ``updates:`` block format and the legacy flat format), scans Python files
    for security incidents, generates deterministic patches, verifies them, and
    opens pull requests for verified fixes.

    When running in GitHub Actions, uses the ``GITHUB_TOKEN`` and ``gh`` CLI to
    create PRs with the labels, reviewers, and assignees configured in ``.aion.yaml``.
    """
    root = target if target.is_dir() else target.parent

    # Load configuration - prefer v2 update configs, fall back to legacy
    try:
        configs = load_update_configs(root)
    except ConfigError as exc:
        raise typer.BadParameter(str(exc)) from exc

    if not configs:
        stdout_console.print("[yellow]No AION update configuration found. Using defaults.[/yellow]")
        configs = [UpdateConfig()]

    all_results: dict[str, AutoUpdateResult] = {}

    for idx, update_config in enumerate(configs):
        config_label = update_config.directory if len(configs) > 1 else "default"
        stderr_console.print(f"[bold]Processing update config [{idx + 1}/{len(configs)}]: {config_label}[/bold]")

        engine = AutoUpdateEngine(root=root, update_config=update_config)
        result = engine.run(dry_run=dry_run)
        all_results[config_label] = result

    # Aggregate results
    total_incidents = sum(r.incidents_found for r in all_results.values())
    total_patches = sum(r.patches_generated for r in all_results.values())
    total_verified = sum(r.patches_verified for r in all_results.values())
    total_prs = sum(r.prs_created for r in all_results.values())
    total_errors = sum(len(r.errors) for r in all_results.values())

    if output == "json":
        payload = {
            "configs": [
                {
                    "label": label,
                    "files_scanned": r.files_scanned,
                    "incidents_found": r.incidents_found,
                    "patches_generated": r.patches_generated,
                    "patches_verified": r.patches_verified,
                    "prs_created": r.prs_created,
                    "errors": r.errors,
                }
                for label, r in all_results.items()
            ],
            "totals": {
                "incidents_found": total_incidents,
                "patches_generated": total_patches,
                "patches_verified": total_verified,
                "prs_created": total_prs,
                "errors": total_errors,
            },
            "dry_run": dry_run,
        }
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    # Rich text output
    mode = "[yellow]DRY RUN[/yellow]" if dry_run else "[green]LIVE[/green]"
    stdout_console.print(
        Panel(
            f"Mode: {mode}\n"
            f"Configs: {len(all_results)}\n"
            f"Incidents found: {total_incidents}\n"
            f"Patches generated: {total_patches}\n"
            f"Patches verified: {total_verified}\n"
            f"PRs created: {total_prs}\n"
            f"Errors: {total_errors}",
            title="AION Auto-Update",
        )
    )

    if total_prs == 0 and not dry_run:
        stderr_console.print("[dim]No verified fixes to submit as PRs.[/dim]")

    raise typer.Exit(code=0 if total_errors == 0 else 1)


def _resolve_target_files(target: Path, extra_ignore_patterns: list[str] | None = None) -> list[Path]:
    extra_ignore_patterns = extra_ignore_patterns or []
    if target.is_file():
        return [target] if target.suffix == ".py" else []
    return sorted(
        path
        for path in target.rglob("*.py")
        if not any(part in EXCLUDED_DIRS for part in path.parts)
        if not _matches_any_pattern(path, target, extra_ignore_patterns)
    )


def _matches_any_pattern(path: Path, root: Path, patterns: list[str]) -> bool:
    try:
        relative = path.relative_to(root if root.is_dir() else root.parent).as_posix()
    except ValueError:
        relative = path.as_posix()
    for pattern in patterns:
        if Path(relative).match(pattern) or Path(path.name).match(pattern):
            return True
    return False


def _resolve_api_key(provider: Provider) -> str | None:
    if provider == Provider.anthropic:
        return os.getenv("ANTHROPIC_API_KEY")
    if provider == Provider.openai:
        return os.getenv("OPENAI_API_KEY")
    if provider == Provider.gemini:
        return os.getenv("GEMINI_API_KEY")
    if provider == Provider.azure:
        return os.getenv("AZURE_OPENAI_API_KEY")
    if provider == Provider.deepseek:
        return os.getenv("DEEPSEEK_API_KEY")
    if provider == Provider.qwen:
        return os.getenv("QWEN_API_KEY")
    return None


def _missing_api_key_message(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "ANTHROPIC_API_KEY is not set. Export it before running, for example: export ANTHROPIC_API_KEY=your_key"
    if provider == Provider.openai:
        return "OPENAI_API_KEY is not set. Export it before running, for example: export OPENAI_API_KEY=your_key"
    if provider == Provider.gemini:
        return "GEMINI_API_KEY is not set. Export it before running, for example: export GEMINI_API_KEY=your_key"
    if provider == Provider.azure:
        return (
            "AZURE_OPENAI_API_KEY is not set. Export it before running, for example: "
            "export AZURE_OPENAI_API_KEY=your_key\n"
            "Also set the endpoint: export AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com"
        )
    if provider == Provider.deepseek:
        return "DEEPSEEK_API_KEY is not set. Export it before running, for example: export DEEPSEEK_API_KEY=your_key"
    if provider == Provider.qwen:
        return "QWEN_API_KEY is not set. Export it before running, for example: export QWEN_API_KEY=your_key"
    return "Provider API key is not set."


def _default_model_for_provider(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "claude-3-5-sonnet-latest"
    if provider == Provider.openai:
        return "gpt-4.1"
    if provider == Provider.gemini:
        return "gemini-2.0-flash"
    if provider == Provider.azure:
        return "gpt-4"
    if provider == Provider.deepseek:
        return "deepseek-chat"
    if provider == Provider.qwen:
        return "qwen-plus"
    raise ValueError(f"unsupported provider: {provider}")


def _auto_detect_provider() -> Provider:
    """Return the first provider whose API key is available in the environment."""
    if os.getenv("ANTHROPIC_API_KEY"):
        return Provider.anthropic
    if os.getenv("OPENAI_API_KEY"):
        return Provider.openai
    if os.getenv("GEMINI_API_KEY"):
        return Provider.gemini
    if os.getenv("AZURE_OPENAI_API_KEY"):
        return Provider.azure
    if os.getenv("DEEPSEEK_API_KEY"):
        return Provider.deepseek
    if os.getenv("QWEN_API_KEY"):
        return Provider.qwen
    return Provider.anthropic


def _auto_detect_provider_if_available() -> Provider | None:
    for provider in Provider:
        if _resolve_api_key(provider):
            return provider
    return None


def _provider_from_config(config: AppConfig) -> Provider | None:
    if config.provider is None:
        return None
    try:
        return Provider(config.provider)
    except ValueError as exc:
        raise typer.BadParameter(f"unsupported provider in .aion.yaml: {config.provider}") from exc


def _expand_explicit_targets(targets: list[Path]) -> set[str]:
    expanded: set[str] = set()
    for target in targets:
        if target.is_dir():
            for path in target.rglob("*.py"):
                expanded.add(normalize_path(path))
        elif target.suffix == ".py":
            expanded.add(normalize_path(target))
    return expanded


def _detect_ai_generated_files(
    candidates: list[Path],
    explicit_targets: set[str],
    root: Path,
) -> tuple[list[Path], list[str]]:
    warnings: list[str] = []
    if explicit_targets:
        selected = [path for path in candidates if normalize_path(path) in explicit_targets]
        if not selected:
            warnings.append("No Python files matched --ai-generated targets.")
        return selected, warnings

    selected = [path for path in candidates if _has_ai_marker(path) or _git_history_has_ai_marker(path, root)]
    if selected:
        return selected, warnings

    warnings.append("No AI-generated markers found; scanning all Python files.")
    return candidates, warnings


def _has_ai_marker(path: Path) -> bool:
    try:
        content = path.read_text(encoding="utf-8", errors="ignore")[:2000].lower()
    except OSError:
        return False
    return any(marker in content for marker in AI_MARKERS)


def _git_history_has_ai_marker(path: Path, root: Path) -> bool:
    command = [
        "git",
        "-C",
        str(root),
        "log",
        "--format=%an%n%B",
        "--",
        str(path),
    ]
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
    except OSError:
        return False
    if result.returncode != 0:
        return False
    history = result.stdout.lower()
    return "github-copilot" in history or "cursor" in history


def _exit_with_summary(summary: ProjectScanSummary, output: str) -> None:
    if output == "json":
        stdout_console.print_json(summary.model_dump_json())
        raise typer.Exit(code=0)

    for warning in summary.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    if summary.files_scanned == 0:
        stdout_console.print(Panel("No Python files were scanned.", title="AION"))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Target: {summary.target}\nFiles scanned: {summary.files_scanned}\nFindings: {summary.finding_count}\nIncidents: {summary.incident_count}",
            title="AION",
        )
    )

    rendered = False
    for report in summary.sorted_reports():
        if not report.findings:
            continue
        rendered = True
        table = Table(title=report.file)
        table.add_column("Severity")
        table.add_column("Line", justify="right")
        table.add_column("Issue")
        table.add_column("Context Gap")
        table.add_column("Fix")
        for finding in sorted(report.findings, key=_severity_sort_key):
            table.add_row(
                finding.severity,
                str(finding.line),
                finding.issue,
                finding.context_gap,
                finding.fix,
            )
        stdout_console.print(table)

    if not rendered:
        stdout_console.print("[green]No findings reported.[/green]")


def _load_context_profile(target: Path, context_file: Path | None) -> ContextProfile:
    if context_file is not None:
        payload = json.loads(context_file.read_text(encoding="utf-8"))
        return ContextProfile(**payload)
    root = target if target.is_dir() else target.parent
    return ContextExtractor(root=root).extract()


def _load_context_profile_for_event(event: OrchestrationEvent, context_file: Path | None) -> ContextProfile:
    if context_file is not None:
        return _load_context_profile(Path(event.target_file), context_file)
    maybe_context = event.metadata.get("context_file")
    if maybe_context:
        return _load_context_profile(Path(event.target_file), Path(str(maybe_context)))
    return _load_context_profile(Path(event.target_file), None)


def _resolve_event_root(event: OrchestrationEvent) -> Path:
    repo_root = event.metadata.get("repo_root")
    if repo_root:
        return Path(str(repo_root)).resolve()
    return Path(event.target_file).resolve().parent


def _build_detector(root: Path, config: AppConfig | None = None, verbose: bool = False) -> IncidentDetector:
    config = config or load_app_config(root)
    semgrep_runner = SemgrepRunner() if semgrep_available() else None

    provider = _provider_from_config(config) or _auto_detect_provider_if_available()
    llm_analyzer = None
    if provider is not None:
        api_key = _resolve_api_key(provider)
        if api_key:
            llm_analyzer = LLMAnalyzer(
                api_key=api_key,
                model=config.model or _default_model_for_provider(provider),
                provider=provider.value,
                verbose=verbose,
            )

    return IncidentDetector(semgrep_runner=semgrep_runner, llm_analyzer=llm_analyzer)


def _build_orchestrator(root: Path, knowledge_base: KnowledgeBase | None = None) -> Orchestrator:
    config = load_app_config(root)
    kb = knowledge_base or KnowledgeBase(base_dir=root / ".aion" / "knowledge")
    detector = _build_detector(root, config=config)
    return Orchestrator.from_config(config, detector=detector, knowledge_base=kb)

def _accumulate_queue_summary(summary: EventQueueSummary, result: OrchestrationResult) -> None:
    if result.policy.action == "auto_repair_sandbox":
        summary.auto_repair_count += 1
    elif result.policy.action == "needs_human_review":
        summary.human_review_count += 1
    elif result.policy.action == "blocked":
        summary.blocked_count += 1
    if result.sandbox is not None and result.sandbox.verification is not None and result.sandbox.verification.verdict == "verified_fix":
        summary.verified_count += 1
    if result.sandbox is not None and result.sandbox.rollout is not None:
        if result.sandbox.rollout.recommendation == "approved_for_rollout":
            summary.approved_count += 1
        elif result.sandbox.rollout.recommendation == "rollback":
            summary.rollback_count += 1

def _build_repair_session(target: Path, context_profile: ContextProfile) -> RepairSession:
    root = target if target.is_dir() else target.parent
    detector = _build_detector(root)
    generator = PatchGenerator()
    incidents = detector.detect(target, context_profile)
    artifact = generator.generate(target, incidents, context_profile)
    warnings: list[str] = []
    if not incidents:
        warnings.append("No actionable incidents were detected.")
    if incidents and artifact is None:
        warnings.append("Incidents were detected, but no deterministic patch could be generated.")
    return RepairSession(target=normalize_path(target), incidents=incidents, artifact=artifact, warnings=warnings)


def _exit_with_repair_record(record: RepairAttemptRecord, output: str) -> None:
    if output == "json":
        stdout_console.print_json(record.model_dump_json())
        raise typer.Exit(code=0)

    for warning in record.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    if not record.incidents:
        stdout_console.print(Panel(f"Target: {record.target}\nNo actionable incidents detected.", title="AION Repair"))
        raise typer.Exit(code=0)

    incident_table = Table(title="Planned Incidents")
    incident_table.add_column("Type")
    incident_table.add_column("Severity")
    incident_table.add_column("Line", justify="right")
    incident_table.add_column("Strategy")
    for incident in record.incidents:
        incident_table.add_row(
            incident.issue_type,
            incident.severity,
            str(incident.line),
            incident.remediation_strategy or "needs_human_review",
        )
    stdout_console.print(incident_table)

    if record.artifact is None:
        stdout_console.print("[yellow]No patch artifact generated.[/yellow]")
        raise typer.Exit(code=0)

    stdout_console.print(Panel(f"Target: {record.target}\nApplied plans: {len(record.artifact.plans)}", title="Patch Artifact"))
    stdout_console.print(record.artifact.diff or "[yellow]No diff produced.[/yellow]")
    raise typer.Exit(code=0)


def _exit_with_verification(verification: VerificationResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(verification.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Verdict: {verification.verdict}\nSyntax: {verification.syntax_ok}\nSemgrep: {verification.semgrep_ok}\nAssertions: {verification.assertions_ok}",
            title="AION Verify",
        )
    )
    checks = Table(title="Verification Checks")
    checks.add_column("Check")
    checks.add_column("Passed")
    checks.add_column("Details")
    for check in verification.checks:
        checks.add_row(check.name, "yes" if check.passed else "no", check.details)
    stdout_console.print(checks)
    if verification.failure_reasons:
        for reason in verification.failure_reasons:
            stderr_console.print(f"[yellow]warning:[/yellow] {reason}")
    raise typer.Exit(code=0)


def _exit_with_run_incident(result: RunIncidentResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(result.model_dump_json())
        raise typer.Exit(code=0)

    for warning in result.session.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    stdout_console.print(
        Panel(
            f"Target: {result.session.target}\nIncidents: {len(result.session.incidents)}\nArtifact: {'yes' if result.session.artifact else 'no'}",
            title="AION Run Incident",
        )
    )
    if result.session.artifact is not None:
        stdout_console.print(result.session.artifact.diff or "[yellow]No diff produced.[/yellow]")
    if result.verification is not None:
        stdout_console.print(
            Panel(
                f"Verdict: {result.verification.verdict}\nSyntax: {result.verification.syntax_ok}\nSemgrep: {result.verification.semgrep_ok}\nAssertions: {result.verification.assertions_ok}",
                title="Verification",
            )
        )
    raise typer.Exit(code=0)


def _exit_with_orchestration_result(result: OrchestrationResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(result.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Event: {result.event.event_id}\n"
                f"Type: {result.event.event_type}\n"
                f"Target: {result.event.target_file}\n"
                f"Policy: {result.policy.action}"
            ),
            title="AION Process Event",
        )
    )
    reasons = Table(title="Policy Reasons")
    reasons.add_column("Reason")
    for reason in result.policy.reasons or ["No policy reasons recorded."]:
        reasons.add_row(reason)
    stdout_console.print(reasons)

    if result.incidents:
        incidents = Table(title="Incidents")
        incidents.add_column("Type")
        incidents.add_column("Severity")
        incidents.add_column("Confidence")
        for incident in result.incidents:
            incidents.add_row(incident.issue_type, incident.severity, f"{incident.confidence:.2f}")
        stdout_console.print(incidents)

    if result.sandbox is not None:
        verdict = result.sandbox.verification.verdict if result.sandbox.verification is not None else "-"
        rollout = result.sandbox.rollout.recommendation if result.sandbox.rollout is not None else "-"
        stdout_console.print(
            Panel(
                (
                    f"Workspace: {result.sandbox.workspace_root}\n"
                    f"Repo root: {result.sandbox.staged_repo_root}\n"
                    f"Staged file: {result.sandbox.staged_target_file}\n"
                    f"Patch applied: {result.sandbox.patch_applied}\n"
                    f"Verdict: {verdict}\n"
                    f"Rollout: {rollout}"
                ),
                title="Sandbox",
            )
        )
        if result.sandbox.command_results:
            commands = Table(title="Sandbox Commands")
            commands.add_column("Command")
            commands.add_column("Passed")
            commands.add_column("Exit")
            for command in result.sandbox.command_results:
                commands.add_row(command.command, "yes" if command.passed else "no", str(command.exit_code))
            stdout_console.print(commands)
    if result.defense_plan is not None:
        _render_defense_plan(result.defense_plan)

    for warning in result.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")
    raise typer.Exit(code=0)


def _exit_with_event_queue_results(results: list[OrchestrationResult], summary: EventQueueSummary, output: str) -> None:
    payload = {
        "summary": summary.model_dump(),
        "results": [result.model_dump() for result in results],
    }
    if output == "json":
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Events: {summary.total_events}\n"
                f"Auto repair: {summary.auto_repair_count}\n"
                f"Human review: {summary.human_review_count}\n"
                f"Blocked: {summary.blocked_count}\n"
                f"Verified: {summary.verified_count}\n"
                f"Approved: {summary.approved_count}\n"
                f"Rollback: {summary.rollback_count}"
            ),
            title="AION Event Queue",
        )
    )
    table = Table(title="Queue Results")
    table.add_column("Event")
    table.add_column("Type")
    table.add_column("Policy")
    table.add_column("Verified")
    table.add_column("Rollout")
    for result in results:
        verified = (
            result.sandbox is not None
            and result.sandbox.verification is not None
            and result.sandbox.verification.verdict == "verified_fix"
        )
        rollout = result.sandbox.rollout.recommendation if result.sandbox is not None and result.sandbox.rollout is not None else "-"
        table.add_row(
            result.event.event_id,
            result.event.event_type,
            result.policy.action,
            "yes" if verified else "no",
            rollout,
        )
    stdout_console.print(table)
    raise typer.Exit(code=0)

def _exit_with_inbox_item(item: InboxItem, output: str) -> None:
    if output == "json":
        stdout_console.print_json(item.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Item: {item.item_id}\nStatus: {item.status}\nEvent: {item.event.event_type}\nTarget: {item.event.target_file}",
            title="AION Inbox",
        )
    )
    raise typer.Exit(code=0)


def _exit_with_inbox_items(items: list[InboxItem], output: str) -> None:
    if output == "json":
        stdout_console.print_json(json.dumps([item.model_dump() for item in items]))
        raise typer.Exit(code=0)

    table = Table(title="AION Inbox")
    table.add_column("Item")
    table.add_column("Status")
    table.add_column("Event")
    table.add_column("Target")
    for item in items:
        table.add_row(item.item_id, item.status, item.event.event_type, item.event.target_file)
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _exit_with_release_candidate(candidate: ReleaseCandidate, output: str) -> None:
    if output == "json":
        stdout_console.print_json(candidate.model_dump_json())
        raise typer.Exit(code=0)

    phases = ", ".join(f"{phase.name}:{phase.percentage}%{'*' if phase.completed else ''}" for phase in candidate.phases)
    stdout_console.print(
        Panel(
            (
                f"Candidate: {candidate.candidate_id}\n"
                f"State: {candidate.state}\n"
                f"Recommendation: {candidate.recommendation}\n"
                f"Target: {candidate.target_file}\n"
                f"Phases: {phases or '-'}"
            ),
            title="AION Release",
        )
    )
    raise typer.Exit(code=0)


def _exit_with_release_candidates(candidates: list[ReleaseCandidate], output: str) -> None:
    if output == "json":
        stdout_console.print_json(json.dumps([candidate.model_dump() for candidate in candidates]))
        raise typer.Exit(code=0)

    table = Table(title="AION Releases")
    table.add_column("Candidate")
    table.add_column("State")
    table.add_column("Recommendation")
    table.add_column("Target")
    for candidate in candidates:
        table.add_row(candidate.candidate_id, candidate.state, candidate.recommendation, candidate.target_file)
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _exit_with_defense_plan(defense_plan, output: str) -> None:
    if output == "json":
        stdout_console.print_json(defense_plan.model_dump_json())
        raise typer.Exit(code=0)
    _render_defense_plan(defense_plan)
    raise typer.Exit(code=0)


def _render_defense_plan(defense_plan) -> None:
    stdout_console.print(Panel(defense_plan.strategy, title="Defense Strategy"))
    table = Table(title="Defense Actions")
    table.add_column("Type")
    table.add_column("Target")
    table.add_column("Rationale")
    for action in defense_plan.actions:
        table.add_row(action.action_type, action.target, action.rationale)
    stdout_console.print(table)
    if defense_plan.notes:
        notes = Table(title="Defense Notes")
        notes.add_column("Note")
        for note in defense_plan.notes:
            notes.add_row(note)
        stdout_console.print(notes)
def _exit_with_repair_eval(results, metrics, output: str) -> None:
    payload = {
        "metrics": metrics.summary_payload(),
        "results": [
            {
                "case": result.case.relative_path,
                "has_vuln": result.case.has_vuln,
                "artifact_generated": result.artifact_generated,
                "verification_passed": result.verification_passed,
                "verdict": result.record.verification.verdict if result.record.verification is not None else None,
            }
            for result in results
        ],
    }
    if output == "json":
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Repair success rate: {metrics.repair_success_rate:.2%}\n"
                f"Verification pass rate: {metrics.verification_pass_rate:.2%}\n"
                f"False-fix rate: {metrics.false_fix_rate:.2%}\n"
                f"Rollback rate: {metrics.rollback_rate:.2%}"
            ),
            title="AION Repair Eval",
        )
    )
    table = Table(title="Repair Eval Cases")
    table.add_column("Case")
    table.add_column("Vulnerable")
    table.add_column("Artifact")
    table.add_column("Verified")
    table.add_column("Verdict")
    for result in results:
        table.add_row(
            result.case.relative_path,
            "yes" if result.case.has_vuln else "no",
            "yes" if result.artifact_generated else "no",
            "yes" if result.verification_passed else "no",
            result.record.verification.verdict if result.record.verification is not None else "-",
        )
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _artifact_from_payload(payload: dict[str, object]) -> PatchArtifact:
    if "artifact" in payload:
        return PatchArtifact(**payload["artifact"])
    if "session" in payload and isinstance(payload["session"], dict) and payload["session"].get("artifact") is not None:
        return PatchArtifact(**payload["session"]["artifact"])
    if "verification" in payload and isinstance(payload["verification"], dict) and payload["verification"].get("artifact") is not None:
        return PatchArtifact(**payload["verification"]["artifact"])
    return PatchArtifact(**payload)


def _record_from_run_result(result: RunIncidentResult, context_profile: ContextProfile) -> RepairAttemptRecord:
    return RepairAttemptRecord(
        target=result.session.target,
        created_at=datetime.now(timezone.utc).isoformat(),
        context_profile=context_profile,
        incidents=result.session.incidents,
        artifact=result.session.artifact,
        verification=result.verification,
        warnings=result.session.warnings,
    )


def _apply_verified_repair(record: RepairAttemptRecord) -> Path | None:
    artifact = record.artifact
    verification = record.verification
    if artifact is None or verification is None:
        return None
    if verification.verdict != "verified_fix":
        return None

    target_path = Path(record.target)
    temp_path = target_path.with_name(f".{target_path.name}.aion.tmp")
    temp_path.write_text(artifact.patched_content, encoding="utf-8")
    temp_path.replace(target_path)
    return target_path


def _write_record(record: RepairAttemptRecord, destination: Path) -> None:
    RepairExecutor().write_record(record, destination)


def _severity_sort_key(finding: Finding) -> tuple[int, int]:
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    return order.get(finding.severity, 4), finding.line
