from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .config import AppConfig, ConfigError, load_app_config
from .context_extractor import ContextExtractor
from .evaluation import compute_repair_metrics, evaluate_repair_cases, load_fixture_cases
from .inbox import EventInbox
from .llm_analyzer import LLMAnalyzer, LLMAnalyzerError
from .models import (
    ContextProfile,
    EventQueueSummary,
    Finding,
    InboxItem,
    OrchestrationResult,
    OrchestrationEvent,
    PatchArtifact,
    ProjectScanSummary,
    ReleaseCandidate,
    RepairAttemptRecord,
    RepairSession,
    RunIncidentResult,
    ScanReport,
    VerificationResult,
    normalize_path,
)
from .orchestrator import Orchestrator
from .repair import IncidentDetector, PatchGenerator, RepairExecutor, Verifier
from .release_manager import ReleaseManager
from .risk_heuristics import fallback_reasons
from .semgrep_runner import SemgrepError, SemgrepRunner, semgrep_available
from .webhook import WebhookEventServer

app = typer.Typer(help="AION: The Self-Evolving Code Engine. Code Once, Live Forever.", no_args_is_help=True)
stderr_console = Console(stderr=True)
stdout_console = Console()

AI_MARKERS = (
    "generated by",
    "co-authored-by: github-copilot",
    "github-copilot[bot]",
    "@cursor",
    "cursor ai",
)


class Provider(str, Enum):
    anthropic = "anthropic"
    openai = "openai"


@app.callback()
def main() -> None:
    """AION: The Self-Evolving Code Engine. Code Once, Live Forever."""


@app.command()
def scan(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    ai_generated: list[Path] | None = typer.Option(
        None,
        "--ai-generated",
        help="Explicit files or directories to treat as AI-generated. Can be repeated.",
    ),
    provider: Provider | None = typer.Option(None, "--provider", help="LLM provider: anthropic or openai."),
    model: str | None = typer.Option(None, help="Model name. Defaults depend on provider."),
    output: str = typer.Option("text", "--output", help="text or json"),
    verbose: bool = typer.Option(False, "--verbose", help="Print context and raw prompts to stderr."),
) -> None:
    root = target if target.is_dir() else target.parent
    try:
        config = load_app_config(root)
    except ConfigError as exc:
        raise typer.BadParameter(str(exc)) from exc

    resolved_provider = provider or _provider_from_config(config) or Provider.anthropic

    api_key = _resolve_api_key(resolved_provider)
    if not api_key:
        raise typer.BadParameter(
            _missing_api_key_message(resolved_provider)
        )
    resolved_model = model or config.model or _default_model_for_provider(resolved_provider)

    extractor = ContextExtractor(root=root, extra_ignore_patterns=config.ignore_paths)
    context_profile = extractor.extract()

    if verbose:
        stderr_console.print("[bold]Context profile[/bold]")
        stderr_console.print_json(json.dumps(context_profile.summary_payload(), ensure_ascii=False))

    candidate_files = _resolve_target_files(target, config.ignore_paths)
    if not candidate_files:
        _exit_with_summary(ProjectScanSummary(target=normalize_path(target), warnings=["No Python files found."]), output)

    explicit_targets = _expand_explicit_targets(ai_generated or [])
    files_to_scan, detection_warnings = _detect_ai_generated_files(candidate_files, explicit_targets, root)
    summary = ProjectScanSummary(
        target=normalize_path(target),
        files_scanned=len(files_to_scan),
        warnings=detection_warnings,
    )

    runner = SemgrepRunner()
    has_semgrep = semgrep_available()
    if not has_semgrep:
        summary.warnings.append("semgrep is not installed; falling back to LLM-only mode.")

    analyzer = LLMAnalyzer(api_key=api_key, model=resolved_model, provider=resolved_provider.value, verbose=verbose)
    detector = IncidentDetector()

    for file_path in files_to_scan:
        report = ScanReport(file=normalize_path(file_path), ai_generated=True)
        semgrep_findings = []
        if has_semgrep:
            try:
                semgrep_findings = runner.run(file_path)
            except SemgrepError as exc:
                summary.warnings.append(f"semgrep failed for {file_path.name}: {exc}")
        report.semgrep_findings = semgrep_findings

        if verbose:
            stderr_console.print(f"[bold]Estimated token cost[/bold] {file_path}: {analyzer.estimate_tokens(file_path, context_profile)}")
            if semgrep_findings:
                stderr_console.print("[bold]Semgrep findings[/bold]")
                stderr_console.print_json(
                    json.dumps([finding.model_dump() for finding in semgrep_findings], ensure_ascii=False)
                )

        try:
            reasons = fallback_reasons(file_path, context_profile)
            if verbose and reasons:
                stderr_console.print(f"[bold]Fallback reasons[/bold] {file_path}: {', '.join(reasons)}")

            should_run_llm = (not has_semgrep) or bool(semgrep_findings) or bool(reasons)
            if not should_run_llm:
                report.mode = "semgrep-only"
                report.findings = []
            else:
                report.findings = analyzer.analyze(
                    file_path,
                    context_profile,
                    semgrep_findings,
                    fallback_signals=reasons,
                    console=stderr_console,
                )
                report.mode = "llm-only" if not has_semgrep else "semgrep+llm"
        except LLMAnalyzerError as exc:
            summary.warnings.append(f"LLM analysis failed for {file_path.name}: {exc}")
            report.mode = "semgrep-only" if has_semgrep else "skipped"
        report.incidents = detector.detect(file_path, context_profile)

        summary.reports.append(report)

    _exit_with_summary(summary, output)


@app.command()
def repair(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    artifact_path: Path | None = typer.Option(None, "--artifact-path", resolve_path=True),
    record_path: Path | None = typer.Option(None, "--record-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    plan_only: bool = typer.Option(True, "--plan/--apply", help="Emit a patch artifact without modifying the file."),
) -> None:
    if not plan_only:
        raise typer.BadParameter("Only --plan is supported in the first autonomy release.")

    context_profile = _load_context_profile(target, context_file)
    record = RepairExecutor().run(target, context_profile, verify=False)
    if artifact_path is not None:
        _write_record(record, artifact_path)
    if record_path is not None:
        _write_record(record, record_path)
    _exit_with_repair_record(record, output)


@app.command()
def verify(
    artifact_path: Path = typer.Option(..., "--artifact-path", exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(artifact_path.read_text(encoding="utf-8"))
    artifact = _artifact_from_payload(payload)
    verification = Verifier().verify(artifact)
    _exit_with_verification(verification, output)


@app.command("run-incident")
def run_incident(
    target: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    artifact_path: Path | None = typer.Option(None, "--artifact-path", resolve_path=True),
    record_path: Path | None = typer.Option(None, "--record-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    context_profile = _load_context_profile(target, context_file)
    result = Orchestrator().run_incident(target, context_profile)
    if artifact_path and result.session.artifact is not None:
        artifact_path.write_text(result.session.model_dump_json(indent=2), encoding="utf-8")
    if record_path is not None:
        _write_record(_record_from_run_result(result, context_profile), record_path)
    _exit_with_run_incident(result, output)


@app.command("repair-eval")
def repair_eval(
    fixtures_root: Path = typer.Argument(Path("tests/fixtures"), exists=True, readable=True, resolve_path=True),
    records_dir: Path | None = typer.Option(None, "--records-dir", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    cases = load_fixture_cases(fixtures_root)
    results = evaluate_repair_cases(cases, verify=True, records_dir=records_dir)
    metrics = compute_repair_metrics(results)
    _exit_with_repair_eval(results, metrics, output)


@app.command("process-event")
def process_event(
    event_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    context_file: Path | None = typer.Option(None, "--context-file", exists=True, readable=True, resolve_path=True),
    result_path: Path | None = typer.Option(None, "--result-path", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspace after processing."),
) -> None:
    payload = json.loads(event_file.read_text(encoding="utf-8"))
    event = Orchestrator().ingest_event(payload)
    repo_root = _resolve_event_root(event)
    orchestrator = _build_orchestrator(repo_root)
    context_profile = _load_context_profile_for_event(event, context_file)
    result = orchestrator.process_event(event, context_profile, repo_root=repo_root)
    if result_path is not None:
        result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
    if cleanup_sandbox:
        orchestrator.cleanup_sandbox(result)
    _exit_with_orchestration_result(result, output)


@app.command("process-event-queue")
def process_event_queue(
    queue_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    results_dir: Path | None = typer.Option(None, "--results-dir", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspaces after processing."),
) -> None:
    payload = json.loads(queue_file.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise typer.BadParameter("queue file must contain a JSON array of events")

    events = [Orchestrator().ingest_event(item) for item in payload]
    orchestrators: dict[str, Orchestrator] = {}

    def context_loader(event: OrchestrationEvent) -> ContextProfile:
        metadata_context = event.metadata.get("context_file")
        context_path = Path(str(metadata_context)).resolve() if metadata_context else None
        return _load_context_profile_for_event(event, context_path)

    def repo_root_loader(event: OrchestrationEvent) -> Path:
        return _resolve_event_root(event)

    results: list[OrchestrationResult] = []
    summary = EventQueueSummary(total_events=len(events))

    for event in events:
        repo_root = repo_root_loader(event)
        key = normalize_path(repo_root)
        orchestrator = orchestrators.setdefault(key, _build_orchestrator(repo_root))
        context_profile = context_loader(event)
        result = orchestrator.process_event(event, context_profile, repo_root=repo_root)
        results.append(result)
        _accumulate_queue_summary(summary, result)
        if results_dir is not None:
            results_dir.mkdir(parents=True, exist_ok=True)
            result_path = results_dir / f"{event.event_id}.json"
            result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
        if cleanup_sandbox:
            orchestrator.cleanup_sandbox(result)

    _exit_with_event_queue_results(results, summary, output)


@app.command("enqueue-event")
def enqueue_event(
    event_file: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(event_file.read_text(encoding="utf-8"))
    event = Orchestrator().ingest_event(payload)
    item = EventInbox(inbox_root).enqueue(event)
    _exit_with_inbox_item(item, output)


@app.command("list-inbox")
def list_inbox(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    status: str | None = typer.Option(None, "--status", help="pending, processed, or failed"),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    items = EventInbox(inbox_root).list_items(status=status)
    _exit_with_inbox_items(items, output)


@app.command("process-inbox")
def process_inbox(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
    cleanup_sandbox: bool = typer.Option(False, "--cleanup-sandbox/--keep-sandbox", help="Remove sandbox workspaces after processing."),
) -> None:
    inbox = EventInbox(inbox_root)
    pending = inbox.list_items(status="pending")
    orchestrators: dict[str, Orchestrator] = {}
    results: list[OrchestrationResult] = []
    summary = EventQueueSummary(total_events=len(pending))

    for item in pending:
        try:
            repo_root = _resolve_event_root(item.event)
            key = normalize_path(repo_root)
            orchestrator = orchestrators.setdefault(key, _build_orchestrator(repo_root))
            context_profile = _load_context_profile_for_event(item.event, None)
            result = orchestrator.process_event(item.event, context_profile, repo_root=repo_root)
            result_path = inbox.result_file(item)
            result_path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
            inbox.mark_processed(item, result_path)
            results.append(result)
            _accumulate_queue_summary(summary, result)
            if cleanup_sandbox:
                orchestrator.cleanup_sandbox(result)
        except Exception as exc:  # noqa: BLE001
            inbox.mark_failed(item, str(exc))

    _exit_with_event_queue_results(results, summary, output)


@app.command("create-release-candidate")
def create_release_candidate(
    result_path: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    payload = json.loads(result_path.read_text(encoding="utf-8"))
    result = OrchestrationResult(**payload)
    candidate = ReleaseManager(releases_root).create_candidate(result)
    _exit_with_release_candidate(candidate, output)


@app.command("list-releases")
def list_releases(
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    state: str | None = typer.Option(None, "--state", help="candidate, approved, executing, completed, rejected, rolled_back"),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidates = ReleaseManager(releases_root).list_candidates(state=state)
    _exit_with_release_candidates(candidates, output)


@app.command("approve-release")
def approve_release(
    candidate_id: str = typer.Argument(...),
    approver: str = typer.Option(..., "--approver"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).approve(candidate_id, approver)
    _exit_with_release_candidate(candidate, output)


@app.command("reject-release")
def reject_release(
    candidate_id: str = typer.Argument(...),
    approver: str = typer.Option(..., "--approver"),
    reason: str = typer.Option(..., "--reason"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).reject(candidate_id, approver, reason)
    _exit_with_release_candidate(candidate, output)


@app.command("advance-release")
def advance_release(
    candidate_id: str = typer.Argument(...),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).advance(candidate_id)
    _exit_with_release_candidate(candidate, output)


@app.command("rollback-release")
def rollback_release(
    candidate_id: str = typer.Argument(...),
    reason: str = typer.Option(..., "--reason"),
    releases_root: Path = typer.Option(Path(".aion/releases"), "--releases-root", resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    candidate = ReleaseManager(releases_root).rollback(candidate_id, reason)
    _exit_with_release_candidate(candidate, output)


@app.command("plan-defense")
def plan_defense(
    result_path: Path = typer.Argument(..., exists=True, readable=True, resolve_path=True),
    output: str = typer.Option("text", "--output", help="text or json"),
) -> None:
    result = OrchestrationResult(**json.loads(result_path.read_text(encoding="utf-8")))
    if result.defense_plan is None:
        event_root = _resolve_event_root(result.event)
        orchestrator = _build_orchestrator(event_root)
        context_profile = _load_context_profile_for_event(result.event, None)
        result = orchestrator.process_event(result.event, context_profile, repo_root=event_root)
    _exit_with_defense_plan(result.defense_plan, output)


@app.command("serve-webhook")
def serve_webhook(
    inbox_root: Path = typer.Option(Path(".aion/inbox"), "--inbox-root", resolve_path=True),
    host: str = typer.Option("127.0.0.1", "--host"),
    port: int = typer.Option(8080, "--port"),
    max_events: int | None = typer.Option(None, "--max-events", min=1),
) -> None:
    server = WebhookEventServer((host, port), inbox_root)
    server.max_events = max_events
    stdout_console.print(Panel(f"Listening on http://{host}:{server.server_port}/events", title="AION Webhook"))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    raise typer.Exit(code=0)


def _resolve_target_files(target: Path, extra_ignore_patterns: list[str] | None = None) -> list[Path]:
    extra_ignore_patterns = extra_ignore_patterns or []
    if target.is_file():
        return [target] if target.suffix == ".py" else []
    return sorted(
        path
        for path in target.rglob("*.py")
        if not any(part in {".git", ".venv", "venv", "node_modules", "__pycache__"} for part in path.parts)
        if not _matches_any_pattern(path, target, extra_ignore_patterns)
    )


def _matches_any_pattern(path: Path, root: Path, patterns: list[str]) -> bool:
    try:
        relative = path.relative_to(root if root.is_dir() else root.parent).as_posix()
    except ValueError:
        relative = path.as_posix()
    for pattern in patterns:
        if Path(relative).match(pattern) or Path(path.name).match(pattern):
            return True
    return False


def _resolve_api_key(provider: Provider) -> str | None:
    if provider == Provider.anthropic:
        return os.getenv("ANTHROPIC_API_KEY")
    if provider == Provider.openai:
        return os.getenv("OPENAI_API_KEY")
    return None


def _missing_api_key_message(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "ANTHROPIC_API_KEY is not set. Export it before running, for example: export ANTHROPIC_API_KEY=your_key"
    if provider == Provider.openai:
        return "OPENAI_API_KEY is not set. Export it before running, for example: export OPENAI_API_KEY=your_key"
    return "Provider API key is not set."


def _default_model_for_provider(provider: Provider) -> str:
    if provider == Provider.anthropic:
        return "claude-3-5-sonnet-latest"
    if provider == Provider.openai:
        return "gpt-4.1"
    raise ValueError(f"unsupported provider: {provider}")


def _provider_from_config(config: AppConfig) -> Provider | None:
    if config.provider is None:
        return None
    try:
        return Provider(config.provider)
    except ValueError as exc:
        raise typer.BadParameter(f"unsupported provider in .aion.yaml: {config.provider}") from exc


def _expand_explicit_targets(targets: list[Path]) -> set[str]:
    expanded: set[str] = set()
    for target in targets:
        if target.is_dir():
            for path in target.rglob("*.py"):
                expanded.add(normalize_path(path))
        elif target.suffix == ".py":
            expanded.add(normalize_path(target))
    return expanded


def _detect_ai_generated_files(
    candidates: list[Path],
    explicit_targets: set[str],
    root: Path,
) -> tuple[list[Path], list[str]]:
    warnings: list[str] = []
    if explicit_targets:
        selected = [path for path in candidates if normalize_path(path) in explicit_targets]
        if not selected:
            warnings.append("No Python files matched --ai-generated targets.")
        return selected, warnings

    selected = [path for path in candidates if _has_ai_marker(path) or _git_history_has_ai_marker(path, root)]
    if selected:
        return selected, warnings

    warnings.append("No AI-generated markers found; scanning all Python files.")
    return candidates, warnings


def _has_ai_marker(path: Path) -> bool:
    try:
        content = path.read_text(encoding="utf-8", errors="ignore")[:2000].lower()
    except OSError:
        return False
    return any(marker in content for marker in AI_MARKERS)


def _git_history_has_ai_marker(path: Path, root: Path) -> bool:
    command = [
        "git",
        "-C",
        str(root),
        "log",
        "--format=%an%n%B",
        "--",
        str(path),
    ]
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
    except OSError:
        return False
    if result.returncode != 0:
        return False
    history = result.stdout.lower()
    return "github-copilot" in history or "cursor" in history


def _exit_with_summary(summary: ProjectScanSummary, output: str) -> None:
    if output == "json":
        stdout_console.print_json(summary.model_dump_json())
        raise typer.Exit(code=0)

    for warning in summary.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    if summary.files_scanned == 0:
        stdout_console.print(Panel("No Python files were scanned.", title="AION"))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Target: {summary.target}\nFiles scanned: {summary.files_scanned}\nFindings: {summary.finding_count}\nIncidents: {summary.incident_count}",
            title="AION",
        )
    )

    rendered = False
    for report in summary.sorted_reports():
        if not report.findings:
            continue
        rendered = True
        table = Table(title=report.file)
        table.add_column("Severity")
        table.add_column("Line", justify="right")
        table.add_column("Issue")
        table.add_column("Context Gap")
        table.add_column("Fix")
        for finding in sorted(report.findings, key=_severity_sort_key):
            table.add_row(
                finding.severity,
                str(finding.line),
                finding.issue,
                finding.context_gap,
                finding.fix,
            )
        stdout_console.print(table)

    if not rendered:
        stdout_console.print("[green]No findings reported.[/green]")


def _load_context_profile(target: Path, context_file: Path | None) -> ContextProfile:
    if context_file is not None:
        payload = json.loads(context_file.read_text(encoding="utf-8"))
        return ContextProfile(**payload)
    root = target if target.is_dir() else target.parent
    return ContextExtractor(root=root).extract()


def _load_context_profile_for_event(event: OrchestrationEvent, context_file: Path | None) -> ContextProfile:
    if context_file is not None:
        return _load_context_profile(Path(event.target_file), context_file)
    maybe_context = event.metadata.get("context_file")
    if maybe_context:
        return _load_context_profile(Path(event.target_file), Path(str(maybe_context)))
    return _load_context_profile(Path(event.target_file), None)


def _resolve_event_root(event: OrchestrationEvent) -> Path:
    repo_root = event.metadata.get("repo_root")
    if repo_root:
        return Path(str(repo_root)).resolve()
    return Path(event.target_file).resolve().parent


def _build_orchestrator(root: Path) -> Orchestrator:
    config = load_app_config(root)
    return Orchestrator.from_config(config)


def _accumulate_queue_summary(summary: EventQueueSummary, result: OrchestrationResult) -> None:
    if result.policy.action == "auto_repair_sandbox":
        summary.auto_repair_count += 1
    elif result.policy.action == "needs_human_review":
        summary.human_review_count += 1
    elif result.policy.action == "blocked":
        summary.blocked_count += 1
    if result.sandbox is not None and result.sandbox.verification is not None and result.sandbox.verification.verdict == "verified_fix":
        summary.verified_count += 1
    if result.sandbox is not None and result.sandbox.rollout is not None:
        if result.sandbox.rollout.recommendation == "approved_for_rollout":
            summary.approved_count += 1
        elif result.sandbox.rollout.recommendation == "rollback":
            summary.rollback_count += 1


def _build_repair_session(target: Path, context_profile: ContextProfile) -> RepairSession:
    detector = IncidentDetector()
    generator = PatchGenerator()
    incidents = detector.detect(target, context_profile)
    artifact = generator.generate(target, incidents, context_profile)
    warnings: list[str] = []
    if not incidents:
        warnings.append("No actionable incidents were detected.")
    if incidents and artifact is None:
        warnings.append("Incidents were detected, but no deterministic patch could be generated.")
    return RepairSession(target=normalize_path(target), incidents=incidents, artifact=artifact, warnings=warnings)


def _exit_with_repair_record(record: RepairAttemptRecord, output: str) -> None:
    if output == "json":
        stdout_console.print_json(record.model_dump_json())
        raise typer.Exit(code=0)

    for warning in record.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    if not record.incidents:
        stdout_console.print(Panel(f"Target: {record.target}\nNo actionable incidents detected.", title="AION Repair"))
        raise typer.Exit(code=0)

    incident_table = Table(title="Planned Incidents")
    incident_table.add_column("Type")
    incident_table.add_column("Severity")
    incident_table.add_column("Line", justify="right")
    incident_table.add_column("Strategy")
    for incident in record.incidents:
        incident_table.add_row(
            incident.issue_type,
            incident.severity,
            str(incident.line),
            incident.remediation_strategy or "needs_human_review",
        )
    stdout_console.print(incident_table)

    if record.artifact is None:
        stdout_console.print("[yellow]No patch artifact generated.[/yellow]")
        raise typer.Exit(code=0)

    stdout_console.print(Panel(f"Target: {record.target}\nApplied plans: {len(record.artifact.plans)}", title="Patch Artifact"))
    stdout_console.print(record.artifact.diff or "[yellow]No diff produced.[/yellow]")
    raise typer.Exit(code=0)


def _exit_with_verification(verification: VerificationResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(verification.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Verdict: {verification.verdict}\nSyntax: {verification.syntax_ok}\nSemgrep: {verification.semgrep_ok}\nAssertions: {verification.assertions_ok}",
            title="AION Verify",
        )
    )
    checks = Table(title="Verification Checks")
    checks.add_column("Check")
    checks.add_column("Passed")
    checks.add_column("Details")
    for check in verification.checks:
        checks.add_row(check.name, "yes" if check.passed else "no", check.details)
    stdout_console.print(checks)
    if verification.failure_reasons:
        for reason in verification.failure_reasons:
            stderr_console.print(f"[yellow]warning:[/yellow] {reason}")
    raise typer.Exit(code=0)


def _exit_with_run_incident(result: RunIncidentResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(result.model_dump_json())
        raise typer.Exit(code=0)

    for warning in result.session.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")

    stdout_console.print(
        Panel(
            f"Target: {result.session.target}\nIncidents: {len(result.session.incidents)}\nArtifact: {'yes' if result.session.artifact else 'no'}",
            title="AION Run Incident",
        )
    )
    if result.session.artifact is not None:
        stdout_console.print(result.session.artifact.diff or "[yellow]No diff produced.[/yellow]")
    if result.verification is not None:
        stdout_console.print(
            Panel(
                f"Verdict: {result.verification.verdict}\nSyntax: {result.verification.syntax_ok}\nSemgrep: {result.verification.semgrep_ok}\nAssertions: {result.verification.assertions_ok}",
                title="Verification",
            )
        )
    raise typer.Exit(code=0)


def _exit_with_orchestration_result(result: OrchestrationResult, output: str) -> None:
    if output == "json":
        stdout_console.print_json(result.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Event: {result.event.event_id}\n"
                f"Type: {result.event.event_type}\n"
                f"Target: {result.event.target_file}\n"
                f"Policy: {result.policy.action}"
            ),
            title="AION Process Event",
        )
    )
    reasons = Table(title="Policy Reasons")
    reasons.add_column("Reason")
    for reason in result.policy.reasons or ["No policy reasons recorded."]:
        reasons.add_row(reason)
    stdout_console.print(reasons)

    if result.incidents:
        incidents = Table(title="Incidents")
        incidents.add_column("Type")
        incidents.add_column("Severity")
        incidents.add_column("Confidence")
        for incident in result.incidents:
            incidents.add_row(incident.issue_type, incident.severity, f"{incident.confidence:.2f}")
        stdout_console.print(incidents)

    if result.sandbox is not None:
        verdict = result.sandbox.verification.verdict if result.sandbox.verification is not None else "-"
        rollout = result.sandbox.rollout.recommendation if result.sandbox.rollout is not None else "-"
        stdout_console.print(
            Panel(
                (
                    f"Workspace: {result.sandbox.workspace_root}\n"
                    f"Repo root: {result.sandbox.staged_repo_root}\n"
                    f"Staged file: {result.sandbox.staged_target_file}\n"
                    f"Patch applied: {result.sandbox.patch_applied}\n"
                    f"Verdict: {verdict}\n"
                    f"Rollout: {rollout}"
                ),
                title="Sandbox",
            )
        )
        if result.sandbox.command_results:
            commands = Table(title="Sandbox Commands")
            commands.add_column("Command")
            commands.add_column("Passed")
            commands.add_column("Exit")
            for command in result.sandbox.command_results:
                commands.add_row(command.command, "yes" if command.passed else "no", str(command.exit_code))
            stdout_console.print(commands)
    if result.defense_plan is not None:
        _render_defense_plan(result.defense_plan)

    for warning in result.warnings:
        stderr_console.print(f"[yellow]warning:[/yellow] {warning}")
    raise typer.Exit(code=0)


def _exit_with_event_queue_results(results: list[OrchestrationResult], summary: EventQueueSummary, output: str) -> None:
    payload = {
        "summary": summary.model_dump(),
        "results": [result.model_dump() for result in results],
    }
    if output == "json":
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Events: {summary.total_events}\n"
                f"Auto repair: {summary.auto_repair_count}\n"
                f"Human review: {summary.human_review_count}\n"
                f"Blocked: {summary.blocked_count}\n"
                f"Verified: {summary.verified_count}\n"
                f"Approved: {summary.approved_count}\n"
                f"Rollback: {summary.rollback_count}"
            ),
            title="AION Event Queue",
        )
    )
    table = Table(title="Queue Results")
    table.add_column("Event")
    table.add_column("Type")
    table.add_column("Policy")
    table.add_column("Verified")
    table.add_column("Rollout")
    for result in results:
        verified = (
            result.sandbox is not None
            and result.sandbox.verification is not None
            and result.sandbox.verification.verdict == "verified_fix"
        )
        rollout = result.sandbox.rollout.recommendation if result.sandbox is not None and result.sandbox.rollout is not None else "-"
        table.add_row(
            result.event.event_id,
            result.event.event_type,
            result.policy.action,
            "yes" if verified else "no",
            rollout,
        )
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _exit_with_inbox_item(item: InboxItem, output: str) -> None:
    if output == "json":
        stdout_console.print_json(item.model_dump_json())
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            f"Item: {item.item_id}\nStatus: {item.status}\nEvent: {item.event.event_type}\nTarget: {item.event.target_file}",
            title="AION Inbox",
        )
    )
    raise typer.Exit(code=0)


def _exit_with_inbox_items(items: list[InboxItem], output: str) -> None:
    if output == "json":
        stdout_console.print_json(json.dumps([item.model_dump() for item in items]))
        raise typer.Exit(code=0)

    table = Table(title="AION Inbox")
    table.add_column("Item")
    table.add_column("Status")
    table.add_column("Event")
    table.add_column("Target")
    for item in items:
        table.add_row(item.item_id, item.status, item.event.event_type, item.event.target_file)
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _exit_with_release_candidate(candidate: ReleaseCandidate, output: str) -> None:
    if output == "json":
        stdout_console.print_json(candidate.model_dump_json())
        raise typer.Exit(code=0)

    phases = ", ".join(f"{phase.name}:{phase.percentage}%{'*' if phase.completed else ''}" for phase in candidate.phases)
    stdout_console.print(
        Panel(
            (
                f"Candidate: {candidate.candidate_id}\n"
                f"State: {candidate.state}\n"
                f"Recommendation: {candidate.recommendation}\n"
                f"Target: {candidate.target_file}\n"
                f"Phases: {phases or '-'}"
            ),
            title="AION Release",
        )
    )
    raise typer.Exit(code=0)


def _exit_with_release_candidates(candidates: list[ReleaseCandidate], output: str) -> None:
    if output == "json":
        stdout_console.print_json(json.dumps([candidate.model_dump() for candidate in candidates]))
        raise typer.Exit(code=0)

    table = Table(title="AION Releases")
    table.add_column("Candidate")
    table.add_column("State")
    table.add_column("Recommendation")
    table.add_column("Target")
    for candidate in candidates:
        table.add_row(candidate.candidate_id, candidate.state, candidate.recommendation, candidate.target_file)
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _exit_with_defense_plan(defense_plan, output: str) -> None:
    if output == "json":
        stdout_console.print_json(defense_plan.model_dump_json())
        raise typer.Exit(code=0)
    _render_defense_plan(defense_plan)
    raise typer.Exit(code=0)


def _render_defense_plan(defense_plan) -> None:
    stdout_console.print(Panel(defense_plan.strategy, title="Defense Strategy"))
    table = Table(title="Defense Actions")
    table.add_column("Type")
    table.add_column("Target")
    table.add_column("Rationale")
    for action in defense_plan.actions:
        table.add_row(action.action_type, action.target, action.rationale)
    stdout_console.print(table)
    if defense_plan.notes:
        notes = Table(title="Defense Notes")
        notes.add_column("Note")
        for note in defense_plan.notes:
            notes.add_row(note)
        stdout_console.print(notes)


def _exit_with_repair_eval(results, metrics, output: str) -> None:
    payload = {
        "metrics": metrics.summary_payload(),
        "results": [
            {
                "case": result.case.relative_path,
                "has_vuln": result.case.has_vuln,
                "artifact_generated": result.artifact_generated,
                "verification_passed": result.verification_passed,
                "verdict": result.record.verification.verdict if result.record.verification is not None else None,
            }
            for result in results
        ],
    }
    if output == "json":
        stdout_console.print_json(json.dumps(payload))
        raise typer.Exit(code=0)

    stdout_console.print(
        Panel(
            (
                f"Repair success rate: {metrics.repair_success_rate:.2%}\n"
                f"Verification pass rate: {metrics.verification_pass_rate:.2%}\n"
                f"False-fix rate: {metrics.false_fix_rate:.2%}\n"
                f"Rollback rate: {metrics.rollback_rate:.2%}"
            ),
            title="AION Repair Eval",
        )
    )
    table = Table(title="Repair Eval Cases")
    table.add_column("Case")
    table.add_column("Vulnerable")
    table.add_column("Artifact")
    table.add_column("Verified")
    table.add_column("Verdict")
    for result in results:
        table.add_row(
            result.case.relative_path,
            "yes" if result.case.has_vuln else "no",
            "yes" if result.artifact_generated else "no",
            "yes" if result.verification_passed else "no",
            result.record.verification.verdict if result.record.verification is not None else "-",
        )
    stdout_console.print(table)
    raise typer.Exit(code=0)


def _artifact_from_payload(payload: dict[str, object]) -> PatchArtifact:
    if "artifact" in payload:
        return PatchArtifact(**payload["artifact"])
    if "session" in payload and isinstance(payload["session"], dict) and payload["session"].get("artifact") is not None:
        return PatchArtifact(**payload["session"]["artifact"])
    if "verification" in payload and isinstance(payload["verification"], dict) and payload["verification"].get("artifact") is not None:
        return PatchArtifact(**payload["verification"]["artifact"])
    return PatchArtifact(**payload)


def _record_from_run_result(result: RunIncidentResult, context_profile: ContextProfile) -> RepairAttemptRecord:
    return RepairAttemptRecord(
        target=result.session.target,
        created_at=datetime.now(timezone.utc).isoformat(),
        context_profile=context_profile,
        incidents=result.session.incidents,
        artifact=result.session.artifact,
        verification=result.verification,
        warnings=result.session.warnings,
    )


def _write_record(record: RepairAttemptRecord, destination: Path) -> None:
    RepairExecutor().write_record(record, destination)


def _severity_sort_key(finding: Finding) -> tuple[int, int]:
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    return order.get(finding.severity, 4), finding.line
