from pathlib import Path

import aion.cli as cli_module
from typer.testing import CliRunner

from aion.cli import app
from aion.models import ContextProfile, Finding


def test_scan_requires_anthropic_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target)])

    assert result.exit_code == 2
    assert "ANTHROPIC_API_KEY is not set" in result.output


def test_scan_requires_openai_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "openai"])

    assert result.exit_code == 2
    assert "OPENAI_API_KEY is not set" in result.output


def test_scan_uses_config_file_provider_and_ignores(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    (tmp_path / ".aion.yaml").write_text(
        "\n".join(
            [
                "provider: openai",
                "model: gpt-4.1",
                "ignore_paths:",
                "  - ignored.py",
            ]
        ),
        encoding="utf-8",
    )
    selected = tmp_path / "selected.py"
    selected.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")
    ignored = tmp_path / "ignored.py"
    ignored.write_text('"""Generated by Copilot."""\nprint("y")\n', encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            assert kwargs["provider"] == "openai"
            assert kwargs["model"] == "gpt-4.1"

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert scanned_files == ["selected.py"]


def test_scan_uses_ai_marker_heuristic(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    generated = tmp_path / "generated.py"
    generated.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")
    plain = tmp_path / "plain.py"
    plain.write_text('print("y")\n', encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return [
                Finding(
                    issue="demo",
                    severity="low",
                    line=1,
                    context_gap="Project uses sqlalchemy.",
                    fix="Use the established pattern.",
                    semgrep_rule=None,
                )
            ]

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert scanned_files == ["generated.py"]
    assert "No AI-generated markers found" not in result.output


def test_scan_warns_and_scans_all_when_no_markers(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    first = tmp_path / "a.py"
    first.write_text("print('a')\n", encoding="utf-8")
    second = tmp_path / "b.py"
    second.write_text("print('b')\n", encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert sorted(scanned_files) == ["a.py", "b.py"]
    assert "No AI-generated markers found; scanning all Python files." in result.output


def test_scan_honors_explicit_ai_generated_targets(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    first = tmp_path / "selected.py"
    first.write_text("print('a')\n", encoding="utf-8")
    second = tmp_path / "ignored.py"
    second.write_text("print('b')\n", encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path), "--ai-generated", str(first)])

    assert result.exit_code == 0
    assert scanned_files == ["selected.py"]


def test_scan_auto_detects_openai_provider_from_env(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.setenv("OPENAI_API_KEY", "test-openai-key")
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
    detected_provider: list[str] = []

    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: cli_module.ContextProfile(orm=None, scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            detected_provider.append(kwargs.get("provider", ""))

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(target)])

    assert result.exit_code == 0
    assert detected_provider == ["openai"]


def test_scan_requires_gemini_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "gemini"])

    assert result.exit_code == 2
    assert "GEMINI_API_KEY is not set" in result.output


def test_scan_requires_azure_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "azure"])

    assert result.exit_code == 2
    assert "AZURE_OPENAI_API_KEY is not set" in result.output


def test_scan_excludes_nox_and_site_packages(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    selected = tmp_path / "app.py"
    selected.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")

    # Files that must be excluded
    nox_dir = tmp_path / ".nox" / "build-3-10" / "lib" / "python3.10" / "site-packages" / "pip"
    nox_dir.mkdir(parents=True)
    (nox_dir / "idnadata.py").write_text('"""Generated by Copilot."""\nx = 1\n', encoding="utf-8")

    tox_dir = tmp_path / ".tox" / "py310"
    tox_dir.mkdir(parents=True)
    (tox_dir / "helper.py").write_text('"""Generated by Copilot."""\nx = 2\n', encoding="utf-8")

    scanned_files: list[str] = []

    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path), "--provider", "openai"])

    assert result.exit_code == 0
    assert scanned_files == ["app.py"]
    assert "idnadata.py" not in scanned_files
    assert "helper.py" not in scanned_files


# ---------------------------------------------------------------------------
# snapshot command
# ---------------------------------------------------------------------------


def test_snapshot_creates_snapshot_file(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("print('hello')\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "test"],
    )

    assert result.exit_code == 0
    assert (snaps_dir / "test.json").exists()
    assert "Snapshot" in result.output


def test_snapshot_json_output(tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--output", "json"],
    )

    assert result.exit_code == 0
    data = json.loads(result.output)
    assert "health_score" in data
    assert "incidents" in data


# ---------------------------------------------------------------------------
# drift command
# ---------------------------------------------------------------------------


def test_drift_no_regression(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    # First create a baseline snapshot.
    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    assert result.exit_code == 0
    assert "CLEAN" in result.output


def test_drift_missing_snapshot_fails(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "nonexistent"],
    )

    assert result.exit_code == 2


def test_drift_detects_regression(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    # Introduce a vulnerability.
    target.write_text(
        'import sqlite3\nconn=sqlite3.connect("db")\ncursor=conn.cursor()\n'
        'uid="1"\ncursor.execute(f"SELECT * FROM t WHERE id = \'{uid}\'")\n',
        encoding="utf-8",
    )

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    assert result.exit_code == 1
    assert "REGRESSION" in result.output


# ---------------------------------------------------------------------------
# status command
# ---------------------------------------------------------------------------


def test_status_empty_aion_dir(tmp_path: Path) -> None:
    runner = CliRunner()
    aion_dir = tmp_path / ".aion"

    result = runner.invoke(app, ["status", "--aion-dir", str(aion_dir)])

    assert result.exit_code == 0
    assert "No snapshots" in result.output
    assert "Knowledge base is empty" in result.output


def test_status_shows_snapshots_and_kb(tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    aion_dir = tmp_path / ".aion"
    snaps_dir = aion_dir / "snapshots"
    kb_dir = aion_dir / "knowledge"

    # Create a snapshot and record a KB pattern.
    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    from aion.knowledge_base import KnowledgeBase
    from aion.models import Incident, VerificationResult, PatchArtifact

    kb = KnowledgeBase(base_dir=kb_dir)
    incident = Incident(
        id="test-001",
        target_file="app.py",
        issue_type="hardcoded_secret",
        issue="test",
        severity="critical",
        line=1,
        confidence=0.99,
        remediation_strategy="env_secret",
    )
    artifact = PatchArtifact(
        target_file="app.py",
        original_content="",
        patched_content="",
        diff="",
    )
    verification = VerificationResult(
        artifact=artifact,
        verdict="verified_fix",
        syntax_ok=True,
        semgrep_ok=True,
        assertions_ok=True,
    )
    kb.record_success(incident, verification)

    result = runner.invoke(app, ["status", "--aion-dir", str(aion_dir)])

    assert result.exit_code == 0
    assert "baseline" in result.output
    assert "hardcoded_secret" in result.output
