from pathlib import Path

import aion.cli as cli_module
from typer.testing import CliRunner

from aion.auto_update import AutoUpdateResult
from aion.cli import app
from aion.models import ContextProfile, Finding, Incident


def test_scan_requires_anthropic_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target)])

    assert result.exit_code == 2
    assert "ANTHROPIC_API_KEY is not set" in result.output


def test_scan_requires_openai_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "openai"])

    assert result.exit_code == 2
    assert "OPENAI_API_KEY is not set" in result.output


def test_scan_uses_config_file_provider_and_ignores(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    (tmp_path / ".aion.yaml").write_text(
        "\n".join(
            [
                "provider: openai",
                "model: gpt-4.1",
                "ignore_paths:",
                "  - ignored.py",
            ]
        ),
        encoding="utf-8",
    )
    selected = tmp_path / "selected.py"
    selected.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")
    ignored = tmp_path / "ignored.py"
    ignored.write_text('"""Generated by Copilot."""\nprint("y")\n', encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            assert kwargs["provider"] == "openai"
            assert kwargs["model"] == "gpt-4.1"

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert scanned_files == ["selected.py"]


def test_scan_uses_ai_marker_heuristic(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    generated = tmp_path / "generated.py"
    generated.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")
    plain = tmp_path / "plain.py"
    plain.write_text('print("y")\n', encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return [
                Finding(
                    issue="demo",
                    severity="low",
                    line=1,
                    context_gap="Project uses sqlalchemy.",
                    fix="Use the established pattern.",
                    semgrep_rule=None,
                )
            ]

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert scanned_files == ["generated.py"]
    assert "No AI-generated markers found" not in result.output


def test_scan_warns_and_scans_all_when_no_markers(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    first = tmp_path / "a.py"
    first.write_text("print('a')\n", encoding="utf-8")
    second = tmp_path / "b.py"
    second.write_text("print('b')\n", encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path)])

    assert result.exit_code == 0
    assert sorted(scanned_files) == ["a.py", "b.py"]
    assert "No AI-generated markers found; scanning all Python files." in result.output


def test_scan_honors_explicit_ai_generated_targets(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    first = tmp_path / "selected.py"
    first.write_text("print('a')\n", encoding="utf-8")
    second = tmp_path / "ignored.py"
    second.write_text("print('b')\n", encoding="utf-8")
    scanned_files: list[str] = []

    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=2),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path), "--ai-generated", str(first)])

    assert result.exit_code == 0
    assert scanned_files == ["selected.py"]


def test_scan_converts_llm_findings_into_incidents(monkeypatch, tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "generated.py"
    target.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")

    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm=None, scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            return [
                Finding(
                    issue="Hardcoded secret in generated code",
                    severity="critical",
                    line=1,
                    context_gap="Secrets should come from environment variables.",
                    fix="Load the value with os.getenv().",
                    semgrep_rule=None,
                )
            ]

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(target), "--provider", "openai", "--output", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["reports"][0]["incidents"][0]["issue_type"] == "hardcoded_secret"


def test_scan_auto_detects_openai_provider_from_env(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.setenv("OPENAI_API_KEY", "test-openai-key")
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
    detected_provider: list[str] = []

    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: cli_module.ContextProfile(orm=None, scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            detected_provider.append(kwargs.get("provider", ""))

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(target)])

    assert result.exit_code == 0
    assert detected_provider == ["openai"]


def test_scan_requires_gemini_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "gemini"])

    assert result.exit_code == 2
    assert "GEMINI_API_KEY is not set" in result.output


def test_scan_requires_azure_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "azure"])

    assert result.exit_code == 2
    assert "AZURE_OPENAI_API_KEY is not set" in result.output


def test_scan_requires_deepseek_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "deepseek"])

    assert result.exit_code == 2
    assert "DEEPSEEK_API_KEY is not set" in result.output


def test_scan_requires_qwen_api_key(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")
    monkeypatch.delenv("QWEN_API_KEY", raising=False)

    result = runner.invoke(app, ["scan", str(target), "--provider", "qwen"])

    assert result.exit_code == 2
    assert "QWEN_API_KEY is not set" in result.output


def test_resolve_api_key_for_deepseek(monkeypatch) -> None:
    from aion.cli import Provider, _resolve_api_key

    monkeypatch.setenv("DEEPSEEK_API_KEY", "sk-test-deepseek")
    assert _resolve_api_key(Provider.deepseek) == "sk-test-deepseek"


def test_resolve_api_key_for_qwen(monkeypatch) -> None:
    from aion.cli import Provider, _resolve_api_key

    monkeypatch.setenv("QWEN_API_KEY", "sk-test-qwen")
    assert _resolve_api_key(Provider.qwen) == "sk-test-qwen"


def test_missing_api_key_message_for_deepseek() -> None:
    from aion.cli import Provider, _missing_api_key_message

    msg = _missing_api_key_message(Provider.deepseek)
    assert "DEEPSEEK_API_KEY" in msg


def test_missing_api_key_message_for_qwen() -> None:
    from aion.cli import Provider, _missing_api_key_message

    msg = _missing_api_key_message(Provider.qwen)
    assert "QWEN_API_KEY" in msg


def test_default_model_for_deepseek() -> None:
    from aion.cli import Provider, _default_model_for_provider

    assert _default_model_for_provider(Provider.deepseek) == "deepseek-chat"


def test_default_model_for_qwen() -> None:
    from aion.cli import Provider, _default_model_for_provider

    assert _default_model_for_provider(Provider.qwen) == "qwen-plus"


def test_auto_detect_provider_prefers_deepseek(monkeypatch) -> None:
    from aion.cli import Provider, _auto_detect_provider

    monkeypatch.setenv("DEEPSEEK_API_KEY", "sk-deepseek")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("QWEN_API_KEY", raising=False)

    assert _auto_detect_provider() == Provider.deepseek


def test_auto_detect_provider_prefers_qwen(monkeypatch) -> None:
    from aion.cli import Provider, _auto_detect_provider

    monkeypatch.setenv("QWEN_API_KEY", "sk-qwen")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)

    assert _auto_detect_provider() == Provider.qwen


def test_auto_detect_provider_anthropic_is_fallback(monkeypatch) -> None:
    from aion.cli import Provider, _auto_detect_provider

    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
    monkeypatch.delenv("QWEN_API_KEY", raising=False)

    assert _auto_detect_provider() == Provider.anthropic


def test_provider_enum_has_deepseek_and_qwen() -> None:
    from aion.cli import Provider

    assert Provider.deepseek.value == "deepseek"
    assert Provider.qwen.value == "qwen"


def test_run_incident_uses_built_detector(monkeypatch, tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "sample.py"
    target.write_text("print('hi')\n", encoding="utf-8")

    class FakeDetector:
        def detect(self, target, context_profile):
            return [
                Incident(
                    id="llm-review-1",
                    source="scan",
                    target_file=str(target),
                    issue_type="llm_review",
                    issue="LLM-only review finding",
                    severity="medium",
                    line=1,
                    evidence=["context gap", "suggested review"],
                    confidence=0.75,
                )
            ]

    monkeypatch.setattr(cli_module, "_build_detector", lambda root, config=None, verbose=False: FakeDetector())

    result = runner.invoke(app, ["run-incident", str(target), "--output", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.stdout)
    assert payload["session"]["incidents"][0]["issue_type"] == "llm_review"
    assert payload["session"]["artifact"] is None


def test_scan_excludes_nox_and_site_packages(monkeypatch, tmp_path: Path) -> None:
    runner = CliRunner()
    selected = tmp_path / "app.py"
    selected.write_text('"""Generated by Copilot."""\nprint("x")\n', encoding="utf-8")

    # Files that must be excluded
    nox_dir = tmp_path / ".nox" / "build-3-10" / "lib" / "python3.10" / "site-packages" / "pip"
    nox_dir.mkdir(parents=True)
    (nox_dir / "idnadata.py").write_text('"""Generated by Copilot."""\nx = 1\n', encoding="utf-8")

    tox_dir = tmp_path / ".tox" / "py310"
    tox_dir.mkdir(parents=True)
    (tox_dir / "helper.py").write_text('"""Generated by Copilot."""\nx = 2\n', encoding="utf-8")

    scanned_files: list[str] = []

    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setattr(
        cli_module.ContextExtractor,
        "extract",
        lambda self: ContextProfile(orm="sqlalchemy", scanned_files=1),
    )
    monkeypatch.setattr(cli_module, "semgrep_available", lambda: False)
    monkeypatch.setattr(cli_module, "_git_history_has_ai_marker", lambda path, root: False)

    class FakeAnalyzer:
        def __init__(self, *args, **kwargs):
            pass

        def analyze(self, target, context_profile, semgrep_findings, fallback_signals=None, console=None):
            scanned_files.append(target.name)
            return []

        def estimate_tokens(self, target, context_profile):
            return 1

    monkeypatch.setattr(cli_module, "LLMAnalyzer", FakeAnalyzer)

    result = runner.invoke(app, ["scan", str(tmp_path), "--provider", "openai"])

    assert result.exit_code == 0
    assert scanned_files == ["app.py"]
    assert "idnadata.py" not in scanned_files
    assert "helper.py" not in scanned_files


# ---------------------------------------------------------------------------
# snapshot command
# ---------------------------------------------------------------------------


def test_snapshot_creates_snapshot_file(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("print('hello')\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "test"],
    )

    assert result.exit_code == 0
    assert (snaps_dir / "test.json").exists()
    assert "Snapshot" in result.output


def test_snapshot_json_output(tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--output", "json"],
    )

    assert result.exit_code == 0
    data = json.loads(result.output)
    assert "health_score" in data
    assert "incidents" in data


# ---------------------------------------------------------------------------
# drift command
# ---------------------------------------------------------------------------


def test_drift_no_regression(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    # First create a baseline snapshot.
    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    assert result.exit_code == 0
    assert "CLEAN" in result.output


def test_drift_missing_snapshot_fails(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "nonexistent"],
    )

    assert result.exit_code == 2


def test_drift_detects_regression(tmp_path: Path) -> None:
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"

    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    # Introduce a vulnerability.
    target.write_text(
        'import sqlite3\nconn=sqlite3.connect("db")\ncursor=conn.cursor()\n'
        'uid="1"\ncursor.execute(f"SELECT * FROM t WHERE id = \'{uid}\'")\n',
        encoding="utf-8",
    )

    result = runner.invoke(
        app,
        ["drift", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    assert result.exit_code == 1
    assert "REGRESSION" in result.output


# ---------------------------------------------------------------------------
# status command
# ---------------------------------------------------------------------------


def test_status_empty_aion_dir(tmp_path: Path) -> None:
    runner = CliRunner()
    aion_dir = tmp_path / ".aion"

    result = runner.invoke(app, ["status", "--aion-dir", str(aion_dir)])

    assert result.exit_code == 0
    assert "No snapshots" in result.output
    assert "Knowledge base is empty" in result.output


def test_status_shows_snapshots_and_kb(tmp_path: Path) -> None:
    import json

    runner = CliRunner()
    target = tmp_path / "safe.py"
    target.write_text("x = 1\n", encoding="utf-8")
    aion_dir = tmp_path / ".aion"
    snaps_dir = aion_dir / "snapshots"
    kb_dir = aion_dir / "knowledge"

    # Create a snapshot and record a KB pattern.
    runner.invoke(
        app,
        ["snapshot", str(target), "--snapshots-dir", str(snaps_dir), "--name", "baseline"],
    )

    from aion.knowledge_base import KnowledgeBase
    from aion.models import Incident, VerificationResult, PatchArtifact

    kb = KnowledgeBase(base_dir=kb_dir)
    incident = Incident(
        id="test-001",
        target_file="app.py",
        issue_type="hardcoded_secret",
        issue="test",
        severity="critical",
        line=1,
        confidence=0.99,
        remediation_strategy="env_secret",
    )
    artifact = PatchArtifact(
        target_file="app.py",
        original_content="",
        patched_content="",
        diff="",
    )
    verification = VerificationResult(
        artifact=artifact,
        verdict="verified_fix",
        syntax_ok=True,
        semgrep_ok=True,
        assertions_ok=True,
    )
    kb.record_success(incident, verification)

    result = runner.invoke(app, ["status", "--aion-dir", str(aion_dir)])

    assert result.exit_code == 0
    assert "baseline" in result.output
    assert "hardcoded_secret" in result.output


# ---------------------------------------------------------------------------
# watch command
# ---------------------------------------------------------------------------


def test_watch_seeds_baseline_on_first_run(tmp_path: Path, monkeypatch) -> None:
    """watch with --max-cycles 0 exits immediately after seeding the baseline."""
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"
    knowledge_dir = tmp_path / "knowledge"

    # Patch time.sleep so the test is instant even if max_cycles > 0.
    monkeypatch.setattr("time.sleep", lambda _: None)

    result = runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "0",
            "--interval", "5",
        ],
    )

    assert result.exit_code == 0
    # Baseline snapshot file must have been written.
    assert (snaps_dir / "watch-baseline.json").exists()
    assert "Baseline saved" in result.output


def test_watch_detects_no_drift_when_file_unchanged(tmp_path: Path, monkeypatch) -> None:
    """watch with --max-cycles 1 reports no drift when the target is unchanged."""
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"
    knowledge_dir = tmp_path / "knowledge"

    monkeypatch.setattr("time.sleep", lambda _: None)

    result = runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "1",
            "--interval", "5",
            "--no-auto-repair",
        ],
    )

    assert result.exit_code == 0
    assert "no drift" in result.output


def test_watch_detects_drift_on_new_vulnerability(tmp_path: Path, monkeypatch) -> None:
    """watch with --max-cycles 1 reports drift when a vulnerability is introduced."""
    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"
    knowledge_dir = tmp_path / "knowledge"

    monkeypatch.setattr("time.sleep", lambda _: None)

    # Seed a clean baseline first (max_cycles=0).
    runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "0",
            "--interval", "5",
        ],
    )

    # Introduce a raw SQLite vulnerability.
    target.write_text(
        'import sqlite3\nconn=sqlite3.connect("db")\ncursor=conn.cursor()\n'
        'uid="1"\ncursor.execute(f"SELECT * FROM t WHERE id = \'{uid}\'")\n',
        encoding="utf-8",
    )

    result = runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "1",
            "--interval", "5",
            "--no-auto-repair",
        ],
    )

    assert result.exit_code == 0
    assert "drift detected" in result.output


def test_watch_auto_repair_applies_verified_patch_and_refreshes_baseline(tmp_path: Path, monkeypatch) -> None:
    import json

    monkeypatch.setattr("aion.repair.semgrep_available", lambda: False)
    monkeypatch.setattr("time.sleep", lambda _: None)

    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"
    knowledge_dir = tmp_path / "knowledge"

    runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "0",
            "--interval", "5",
        ],
    )

    target.write_text(
        Path("tests/fixtures/vulnerable/02_hardcoded_secret.py").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "1",
            "--interval", "5",
        ],
    )

    assert result.exit_code == 0
    patched = target.read_text(encoding="utf-8")
    assert 'os.getenv("API_KEY", "")' in patched
    assert "sk-live-demo-secret" not in patched
    assert "Applied verified patch" in result.output

    watch_baseline = json.loads((snaps_dir / "watch-baseline.json").read_text(encoding="utf-8"))
    assert watch_baseline["incidents"] == []


def test_watch_auto_repair_skips_unverified_patch(tmp_path: Path, monkeypatch) -> None:
    from aion.models import PatchArtifact, RepairAttemptRecord, RemediationPlan, VerificationResult

    monkeypatch.setattr("aion.repair.semgrep_available", lambda: False)
    monkeypatch.setattr("time.sleep", lambda _: None)

    runner = CliRunner()
    target = tmp_path / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    snaps_dir = tmp_path / "snaps"
    knowledge_dir = tmp_path / "knowledge"

    runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "0",
            "--interval", "5",
        ],
    )

    vulnerable = (
        "import sqlite3\n\n"
        "def load_user(user_id):\n"
        "    conn = sqlite3.connect('db.sqlite3')\n"
        "    cursor = conn.cursor()\n"
        '    cursor.execute(f"SELECT email FROM users WHERE id = {user_id}")\n'
        "    return cursor.fetchone()\n"
    )
    target.write_text(vulnerable, encoding="utf-8")

    def fake_run(self, target_path, context_profile, verify=True):
        artifact = PatchArtifact(
            incident_ids=["demo"],
            target_file=str(target_path),
            original_content=vulnerable,
            patched_content=vulnerable.replace("email", "username"),
            diff="",
            plans=[
                RemediationPlan(
                    incident_id="demo",
                    target_file=str(target_path),
                    strategy="parameterize_sqlite_query",
                    summary="Replace interpolated sqlite query with a parameterized call.",
                )
            ],
        )
        verification = VerificationResult(
            artifact=artifact,
            verdict="unsafe_patch",
            syntax_ok=True,
            semgrep_ok=True,
            assertions_ok=False,
            failure_reasons=["semantic verification failed"],
        )
        return RepairAttemptRecord(
            target=str(target_path),
            created_at="2026-01-01T00:00:00+00:00",
            context_profile=ContextProfile(),
            incidents=[],
            artifact=artifact,
            verification=verification,
        )

    monkeypatch.setattr(cli_module.RepairExecutor, "run", fake_run)

    result = runner.invoke(
        app,
        [
            "watch",
            str(target),
            "--snapshots-dir", str(snaps_dir),
            "--knowledge-dir", str(knowledge_dir),
            "--max-cycles", "1",
            "--interval", "5",
        ],
    )

    assert result.exit_code == 0
    assert target.read_text(encoding="utf-8") == vulnerable
    assert "No incidents could be auto-repaired" in result.output


# ---------------------------------------------------------------------------
# serve-webhook command
# ---------------------------------------------------------------------------


def test_serve_webhook_starts_and_accepts_event(tmp_path: Path, monkeypatch) -> None:
    """serve-webhook CLI command starts a server and enqueues a POST /events payload."""
    import json
    import threading
    import urllib.request

    from aion.inbox import EventInbox

    inbox_root = tmp_path / "inbox"
    runner = CliRunner()

    # Capture the port printed by the CLI so we can POST to it.
    # We replace WebhookEventServer with a subclass that records the bound port
    # via a threading.Event so the main thread knows when to send the request.
    port_event = threading.Event()
    captured_port: list[int] = []

    original_server_cls = cli_module.WebhookEventServer

    class PatchedWebhookServer(original_server_cls):  # type: ignore[misc]
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            captured_port.append(self.server_port)
            port_event.set()

    monkeypatch.setattr(cli_module, "WebhookEventServer", PatchedWebhookServer)

    # Run the CLI command in a background thread. The server stops after max_events=1.
    cli_results: list = []

    def _run_cli() -> None:
        r = runner.invoke(
            app,
            [
                "serve-webhook",
                "--inbox-root", str(inbox_root),
                "--host", "127.0.0.1",
                "--port", "0",
                "--max-events", "1",
            ],
        )
        cli_results.append(r)

    thread = threading.Thread(target=_run_cli, daemon=True)
    thread.start()

    # Wait until the server is bound.
    port_event.wait(timeout=5)
    assert captured_port, "Server did not bind within timeout"

    payload = json.dumps({"event_type": "runtime_alert", "target_file": "/tmp/demo.py"}).encode()
    req = urllib.request.Request(
        f"http://127.0.0.1:{captured_port[0]}/events",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=5) as resp:
        body = json.loads(resp.read().decode())
    assert body["status"] == "pending"

    thread.join(timeout=5)
    assert cli_results, "CLI thread did not finish"
    assert cli_results[0].exit_code == 0

    items = EventInbox(inbox_root).list_items(status="pending")
    assert len(items) == 1
    assert items[0].event.event_type == "runtime_alert"


# ---------------------------------------------------------------------------
# auto-update command
# ---------------------------------------------------------------------------


def test_auto_update_dry_run_with_no_files(tmp_path: Path, monkeypatch) -> None:
    """auto-update --dry-run exits cleanly when no Python files exist."""
    runner = CliRunner()

    result = runner.invoke(app, ["auto-update", "--target", str(tmp_path), "--dry-run"])
    assert result.exit_code == 0
    assert "Incidents found: 0" in result.output


def test_auto_update_dry_run_with_files_no_config(tmp_path: Path, monkeypatch) -> None:
    """auto-update --dry-run scans files with defaults when no .aion.yaml."""
    runner = CliRunner()
    (tmp_path / "main.py").write_text("x = 1\n")

    def fake_run(self, dry_run=False):
        r = AutoUpdateResult()
        r.files_scanned = 1
        r.incidents_found = 2
        return r

    monkeypatch.setattr(cli_module.AutoUpdateEngine, "run", fake_run)

    result = runner.invoke(app, ["auto-update", "--target", str(tmp_path), "--dry-run"])
    assert result.exit_code == 0
    assert "Incidents found: 2" in result.output


def test_auto_update_json_output(tmp_path: Path, monkeypatch) -> None:
    """auto-update --output json emits structured JSON."""
    import json

    runner = CliRunner()

    def fake_run(self, dry_run=False):
        r = AutoUpdateResult()
        r.files_scanned = 5
        r.incidents_found = 1
        r.patches_generated = 1
        r.patches_verified = 1
        return r

    monkeypatch.setattr(cli_module.AutoUpdateEngine, "run", fake_run)

    result = runner.invoke(app, ["auto-update", "--target", str(tmp_path), "--dry-run", "--output", "json"])
    assert result.exit_code == 0
    # CliRunner mixes stderr ("]: default\n") with stdout (JSON)
    output = result.output
    if "Processing" in output:
        output = output.split("\n", 1)[1]
    payload = json.loads(output)
    assert payload["dry_run"] is True
    assert payload["totals"]["incidents_found"] == 1
    assert payload["totals"]["patches_generated"] == 1
    assert payload["totals"]["patches_verified"] == 1


def test_auto_update_handles_multiple_configs(tmp_path: Path, monkeypatch) -> None:
    """auto-update processes multiple updates blocks."""
    runner = CliRunner()
    (tmp_path / ".aion.yaml").write_text(
        "\n".join(
            [
                "updates:",
                "  - directory: \"/\"",
                "    provider: openai",
                "  - directory: \"/src\"",
                "    provider: qwen",
            ]
        ),
        encoding="utf-8",
    )

    run_count: list[int] = []

    def fake_run(self, dry_run=False):
        run_count.append(1)
        r = AutoUpdateResult()
        r.files_scanned = 2
        r.incidents_found = 0
        return r

    monkeypatch.setattr(cli_module.AutoUpdateEngine, "run", fake_run)

    result = runner.invoke(app, ["auto-update", "--target", str(tmp_path), "--dry-run"])
    assert result.exit_code == 0
    assert len(run_count) == 2  # one per update block


def test_auto_update_error_exit(tmp_path: Path, monkeypatch) -> None:
    """auto-update exits with code 1 when errors occur."""
    runner = CliRunner()

    def fake_run(self, dry_run=False):
        r = AutoUpdateResult()
        r.errors = ["gh CLI not found"]
        return r

    monkeypatch.setattr(cli_module.AutoUpdateEngine, "run", fake_run)

    result = runner.invoke(app, ["auto-update", "--target", str(tmp_path)])
    assert result.exit_code == 1
