name: RepoKeeper Labeler

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: shenxianpeng/.github/.github/workflows/repokeeper-labeler.yml@main
    with:
      repo: ${{ github.repository }}
      issue: ${{ github.event.issue.number || '' }}
      pr: ${{ github.event.pull_request.number || '' }}
    secrets:
      deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
